/* app.c generated by valac 0.56.3, the Vala compiler
 * generated from app.vala, do not modify */

/*
* Copyright (c) 2022 Fyra Labs
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*
*/

#include <libhelium-1.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include "config.h"
#include <glib/gi18n-lib.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>
#include <gtksourceview/gtksource.h>
#include <gtk/gtk.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define ENIGMA_TYPE_APPLICATION (enigma_application_get_type ())
#define ENIGMA_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_APPLICATION, EnigmaApplication))
#define ENIGMA_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_APPLICATION, EnigmaApplicationClass))
#define ENIGMA_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_APPLICATION))
#define ENIGMA_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_APPLICATION))
#define ENIGMA_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_APPLICATION, EnigmaApplicationClass))

typedef struct _EnigmaApplication EnigmaApplication;
typedef struct _EnigmaApplicationClass EnigmaApplicationClass;
typedef struct _EnigmaApplicationPrivate EnigmaApplicationPrivate;
enum  {
	ENIGMA_APPLICATION_0_PROPERTY,
	ENIGMA_APPLICATION_NUM_PROPERTIES
};
static GParamSpec* enigma_application_properties[ENIGMA_APPLICATION_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define ENIGMA_TYPE_MAIN_WINDOW (enigma_main_window_get_type ())
#define ENIGMA_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindow))
#define ENIGMA_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindowClass))
#define ENIGMA_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_MAIN_WINDOW))
#define ENIGMA_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_MAIN_WINDOW))
#define ENIGMA_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindowClass))

typedef struct _EnigmaMainWindow EnigmaMainWindow;
typedef struct _EnigmaMainWindowClass EnigmaMainWindowClass;

struct _EnigmaApplication {
	HeApplication parent_instance;
	EnigmaApplicationPrivate * priv;
};

struct _EnigmaApplicationClass {
	HeApplicationClass parent_class;
};

static gpointer enigma_application_parent_class = NULL;

VALA_EXTERN GType enigma_application_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaApplication, g_object_unref)
static void _g_application_quit_gsimple_action_activate_callback (GSimpleAction* action,
                                                           GVariant* parameter,
                                                           gpointer self);
VALA_EXTERN EnigmaApplication* enigma_application_new (void);
VALA_EXTERN EnigmaApplication* enigma_application_construct (GType object_type);
static gint enigma_application_main (gchar** args,
                              gint args_length1);
static void enigma_application_real_startup (GApplication* base);
VALA_EXTERN EnigmaMainWindow* enigma_main_window_new (HeApplication* application);
VALA_EXTERN EnigmaMainWindow* enigma_main_window_construct (GType object_type,
                                                HeApplication* application);
VALA_EXTERN GType enigma_main_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaMainWindow, g_object_unref)
static void enigma_application_real_activate (GApplication* base);
static void enigma_application_real_open (GApplication* base,
                                   GFile** files,
                                   gint files_length1,
                                   const gchar* hint);
VALA_EXTERN void enigma_main_window_load (EnigmaMainWindow* self,
                              GFile* file);
static GType enigma_application_get_type_once (void);

static const GActionEntry ENIGMA_APPLICATION_app_entries[1] = {{"quit", _g_application_quit_gsimple_action_activate_callback}};

static void
_g_application_quit_gsimple_action_activate_callback (GSimpleAction* action,
                                                      GVariant* parameter,
                                                      gpointer self)
{
#line 21 "../src/app.vala"
	g_application_quit ((GApplication*) self);
#line 120 "app.c"
}

EnigmaApplication*
enigma_application_construct (GType object_type)
{
	EnigmaApplication * self = NULL;
#line 26 "../src/app.vala"
	self = (EnigmaApplication*) he_application_construct (object_type, APP_ID, G_APPLICATION_HANDLES_OPEN);
#line 25 "../src/app.vala"
	return self;
#line 131 "app.c"
}

EnigmaApplication*
enigma_application_new (void)
{
#line 25 "../src/app.vala"
	return enigma_application_construct (ENIGMA_TYPE_APPLICATION);
#line 139 "app.c"
}

static gint
enigma_application_main (gchar** args,
                         gint args_length1)
{
	EnigmaApplication* app = NULL;
	EnigmaApplication* _tmp0_;
	gint result;
#line 30 "../src/app.vala"
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
#line 31 "../src/app.vala"
	textdomain (GETTEXT_PACKAGE);
#line 33 "../src/app.vala"
	_tmp0_ = enigma_application_new ();
#line 33 "../src/app.vala"
	app = _tmp0_;
#line 34 "../src/app.vala"
	result = g_application_run ((GApplication*) app, (gint) args_length1, args);
#line 34 "../src/app.vala"
	_g_object_unref0 (app);
#line 34 "../src/app.vala"
	return result;
#line 163 "app.c"
}

int
main (int argc,
      char ** argv)
{
#line 29 "../src/app.vala"
	return enigma_application_main (argv, argc);
#line 172 "app.c"
}

static void
enigma_application_real_startup (GApplication* base)
{
	EnigmaApplication * self;
	GdkRGBA accent_color = {0};
	GdkRGBA _tmp0_ = {0};
	GdkRGBA _tmp1_;
	HeColorRGBColor _tmp2_ = {0};
	EnigmaMainWindow* _tmp3_;
	EnigmaMainWindow* _tmp4_;
#line 37 "../src/app.vala"
	self = (EnigmaApplication*) base;
#line 38 "../src/app.vala"
	_tmp0_.red = (gfloat) 0;
#line 38 "../src/app.vala"
	accent_color = _tmp0_;
#line 39 "../src/app.vala"
	gdk_rgba_parse (&accent_color, "#268EF9");
#line 40 "../src/app.vala"
	_tmp1_ = accent_color;
#line 40 "../src/app.vala"
	he_color_from_gdk_rgba (&_tmp1_, &_tmp2_);
#line 40 "../src/app.vala"
	he_application_set_default_accent_color ((HeApplication*) self, &_tmp2_);
#line 42 "../src/app.vala"
	g_application_set_resource_base_path ((GApplication*) self, "/co/tauos/Enigma");
#line 44 "../src/app.vala"
	G_APPLICATION_CLASS (enigma_application_parent_class)->startup ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, HE_TYPE_APPLICATION, HeApplication));
#line 46 "../src/app.vala"
	g_type_ensure (gtk_source_view_get_type ());
#line 48 "../src/app.vala"
	g_action_map_add_action_entries ((GActionMap*) self, ENIGMA_APPLICATION_app_entries, (gint) G_N_ELEMENTS (ENIGMA_APPLICATION_app_entries), self);
#line 50 "../src/app.vala"
	_tmp3_ = enigma_main_window_new ((HeApplication*) self);
#line 50 "../src/app.vala"
	g_object_ref_sink (_tmp3_);
#line 50 "../src/app.vala"
	_tmp4_ = _tmp3_;
#line 50 "../src/app.vala"
	_g_object_unref0 (_tmp4_);
#line 215 "app.c"
}

static void
enigma_application_real_activate (GApplication* base)
{
	EnigmaApplication * self;
	GtkWindow* _tmp0_ = NULL;
	GtkWindow* _tmp1_;
	GtkWindow* _tmp2_;
#line 53 "../src/app.vala"
	self = (EnigmaApplication*) base;
#line 54 "../src/app.vala"
	_tmp1_ = gtk_application_get_active_window ((GtkApplication*) self);
#line 54 "../src/app.vala"
	_tmp2_ = _tmp1_;
#line 54 "../src/app.vala"
	_tmp0_ = _tmp2_;
#line 54 "../src/app.vala"
	if (_tmp0_ != NULL) {
#line 54 "../src/app.vala"
		gtk_window_present (_tmp0_);
#line 237 "app.c"
	}
}

static void
enigma_application_real_open (GApplication* base,
                              GFile** files,
                              gint files_length1,
                              const gchar* hint)
{
	EnigmaApplication * self;
	EnigmaMainWindow* _tmp0_;
	EnigmaMainWindow* _tmp1_;
	GFile* _tmp2_;
#line 57 "../src/app.vala"
	self = (EnigmaApplication*) base;
#line 57 "../src/app.vala"
	g_return_if_fail (hint != NULL);
#line 58 "../src/app.vala"
	G_APPLICATION_CLASS (enigma_application_parent_class)->open ((GApplication*) G_TYPE_CHECK_INSTANCE_CAST (self, HE_TYPE_APPLICATION, HeApplication), files, (gint) files_length1, hint);
#line 59 "../src/app.vala"
	_tmp0_ = enigma_main_window_new ((HeApplication*) self);
#line 59 "../src/app.vala"
	g_object_ref_sink (_tmp0_);
#line 59 "../src/app.vala"
	_tmp1_ = _tmp0_;
#line 59 "../src/app.vala"
	_tmp2_ = files[0];
#line 59 "../src/app.vala"
	enigma_main_window_load (_tmp1_, _tmp2_);
#line 59 "../src/app.vala"
	_g_object_unref0 (_tmp1_);
#line 269 "app.c"
}

static void
enigma_application_class_init (EnigmaApplicationClass * klass,
                               gpointer klass_data)
{
#line 20 "../src/app.vala"
	enigma_application_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/app.vala"
	((GApplicationClass *) klass)->startup = (void (*) (GApplication*)) enigma_application_real_startup;
#line 20 "../src/app.vala"
	((GApplicationClass *) klass)->activate = (void (*) (GApplication*)) enigma_application_real_activate;
#line 20 "../src/app.vala"
	((GApplicationClass *) klass)->open = (void (*) (GApplication*, GFile**, gint, const gchar*)) enigma_application_real_open;
#line 284 "app.c"
}

static void
enigma_application_instance_init (EnigmaApplication * self,
                                  gpointer klass)
{
}

 G_GNUC_NO_INLINE static GType
enigma_application_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (EnigmaApplicationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) enigma_application_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EnigmaApplication), 0, (GInstanceInitFunc) enigma_application_instance_init, NULL };
	GType enigma_application_type_id;
	enigma_application_type_id = g_type_register_static (HE_TYPE_APPLICATION, "EnigmaApplication", &g_define_type_info, 0);
	return enigma_application_type_id;
}

GType
enigma_application_get_type (void)
{
	static gsize enigma_application_type_id__once = 0;
	if (g_once_init_enter (&enigma_application_type_id__once)) {
		GType enigma_application_type_id;
		enigma_application_type_id = enigma_application_get_type_once ();
		g_once_init_leave (&enigma_application_type_id__once, enigma_application_type_id);
	}
	return enigma_application_type_id__once;
}

