/* prefs.c generated by valac 0.56.3, the Vala compiler
 * generated from prefs.vala, do not modify */

/*
* Copyright (c) 2022 Fyra Labs
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*
*/

#include <libhelium-1.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define ENIGMA_TYPE_PREFERENCES (enigma_preferences_get_type ())
#define ENIGMA_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_PREFERENCES, EnigmaPreferences))
#define ENIGMA_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_PREFERENCES, EnigmaPreferencesClass))
#define ENIGMA_IS_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_PREFERENCES))
#define ENIGMA_IS_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_PREFERENCES))
#define ENIGMA_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_PREFERENCES, EnigmaPreferencesClass))

typedef struct _EnigmaPreferences EnigmaPreferences;
typedef struct _EnigmaPreferencesClass EnigmaPreferencesClass;
typedef struct _EnigmaPreferencesPrivate EnigmaPreferencesPrivate;
enum  {
	ENIGMA_PREFERENCES_0_PROPERTY,
	ENIGMA_PREFERENCES_NUM_PROPERTIES
};
static GParamSpec* enigma_preferences_properties[ENIGMA_PREFERENCES_NUM_PROPERTIES];

#define ENIGMA_TYPE_MAIN_WINDOW (enigma_main_window_get_type ())
#define ENIGMA_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindow))
#define ENIGMA_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindowClass))
#define ENIGMA_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_MAIN_WINDOW))
#define ENIGMA_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_MAIN_WINDOW))
#define ENIGMA_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindowClass))

typedef struct _EnigmaMainWindow EnigmaMainWindow;
typedef struct _EnigmaMainWindowClass EnigmaMainWindowClass;

#define ENIGMA_TYPE_SETTINGS (enigma_settings_get_type ())
#define ENIGMA_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_SETTINGS, EnigmaSettings))
#define ENIGMA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_SETTINGS, EnigmaSettingsClass))
#define ENIGMA_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_SETTINGS))
#define ENIGMA_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_SETTINGS))
#define ENIGMA_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_SETTINGS, EnigmaSettingsClass))

typedef struct _EnigmaSettings EnigmaSettings;
typedef struct _EnigmaSettingsClass EnigmaSettingsClass;
typedef struct _Block1Data Block1Data;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _EnigmaSettingsPrivate EnigmaSettingsPrivate;

struct _EnigmaPreferences {
	HeSettingsWindow parent_instance;
	EnigmaPreferencesPrivate * priv;
};

struct _EnigmaPreferencesClass {
	HeSettingsWindowClass parent_class;
};

struct _EnigmaPreferencesPrivate {
	GtkCheckButton* sml;
	GtkCheckButton* mid;
	GtkCheckButton* big;
	GtkSwitch* sn;
	GtkSwitch* hcl;
	GtkSwitch* hmb;
};

struct _Block1Data {
	int _ref_count_;
	EnigmaPreferences* self;
	EnigmaSettings* settings;
};

struct _EnigmaSettings {
	GObject parent_instance;
	EnigmaSettingsPrivate * priv;
	GSettings* settings;
};

struct _EnigmaSettingsClass {
	GObjectClass parent_class;
};

static gint EnigmaPreferences_private_offset;
static gpointer enigma_preferences_parent_class = NULL;

VALA_EXTERN GType enigma_preferences_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaPreferences, g_object_unref)
VALA_EXTERN GType enigma_main_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaMainWindow, g_object_unref)
VALA_EXTERN EnigmaPreferences* enigma_preferences_new (EnigmaMainWindow* win);
VALA_EXTERN EnigmaPreferences* enigma_preferences_construct (GType object_type,
                                                 EnigmaMainWindow* win);
VALA_EXTERN GType enigma_settings_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaSettings, g_object_unref)
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
VALA_EXTERN EnigmaSettings* enigma_settings_new (void);
VALA_EXTERN EnigmaSettings* enigma_settings_construct (GType object_type);
VALA_EXTERN const gchar* enigma_settings_get_font_size (EnigmaSettings* self);
static void __lambda4_ (Block1Data* _data1_);
VALA_EXTERN void enigma_settings_set_font_size (EnigmaSettings* self,
                                    const gchar* value);
static void ___lambda4__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
static void __lambda5_ (Block1Data* _data1_);
static void ___lambda5__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
static void __lambda6_ (Block1Data* _data1_);
static void ___lambda6__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
static void __lambda7_ (Block1Data* _data1_);
static void ___lambda7__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
static void enigma_preferences_finalize (GObject * obj);
static GType enigma_preferences_get_type_once (void);

static inline gpointer
enigma_preferences_get_instance_private (EnigmaPreferences* self)
{
	return G_STRUCT_MEMBER_P (self, EnigmaPreferences_private_offset);
}

static Block1Data*
block1_data_ref (Block1Data* _data1_)
{
#line 36 "../src/prefs.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 36 "../src/prefs.vala"
	return _data1_;
#line 167 "prefs.c"
}

static void
block1_data_unref (void * _userdata_)
{
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 36 "../src/prefs.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 177 "prefs.c"
		EnigmaPreferences* self;
#line 36 "../src/prefs.vala"
		self = _data1_->self;
#line 36 "../src/prefs.vala"
		_g_object_unref0 (_data1_->settings);
#line 36 "../src/prefs.vala"
		_g_object_unref0 (self);
#line 36 "../src/prefs.vala"
		g_slice_free (Block1Data, _data1_);
#line 187 "prefs.c"
	}
}

static void
__lambda4_ (Block1Data* _data1_)
{
	EnigmaPreferences* self;
	EnigmaSettings* _tmp0_;
#line 52 "../src/prefs.vala"
	self = _data1_->self;
#line 53 "../src/prefs.vala"
	_tmp0_ = _data1_->settings;
#line 53 "../src/prefs.vala"
	enigma_settings_set_font_size (_tmp0_, "'small'");
#line 202 "prefs.c"
}

static void
___lambda4__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
#line 52 "../src/prefs.vala"
	__lambda4_ (self);
#line 212 "prefs.c"
}

static void
__lambda5_ (Block1Data* _data1_)
{
	EnigmaPreferences* self;
	EnigmaSettings* _tmp0_;
#line 55 "../src/prefs.vala"
	self = _data1_->self;
#line 56 "../src/prefs.vala"
	_tmp0_ = _data1_->settings;
#line 56 "../src/prefs.vala"
	enigma_settings_set_font_size (_tmp0_, "'medium'");
#line 226 "prefs.c"
}

static void
___lambda5__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
#line 55 "../src/prefs.vala"
	__lambda5_ (self);
#line 236 "prefs.c"
}

static void
__lambda6_ (Block1Data* _data1_)
{
	EnigmaPreferences* self;
	EnigmaSettings* _tmp0_;
#line 58 "../src/prefs.vala"
	self = _data1_->self;
#line 59 "../src/prefs.vala"
	_tmp0_ = _data1_->settings;
#line 59 "../src/prefs.vala"
	enigma_settings_set_font_size (_tmp0_, "'large'");
#line 250 "prefs.c"
}

static void
___lambda6__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
#line 58 "../src/prefs.vala"
	__lambda6_ (self);
#line 260 "prefs.c"
}

static void
__lambda7_ (Block1Data* _data1_)
{
	EnigmaPreferences* self;
	EnigmaSettings* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	GQuark _tmp5_ = 0U;
#line 62 "../src/prefs.vala"
	static GQuark _tmp4_label0 = 0;
#line 62 "../src/prefs.vala"
	static GQuark _tmp4_label1 = 0;
#line 61 "../src/prefs.vala"
	self = _data1_->self;
#line 62 "../src/prefs.vala"
	_tmp0_ = _data1_->settings;
#line 62 "../src/prefs.vala"
	_tmp1_ = enigma_settings_get_font_size (_tmp0_);
#line 62 "../src/prefs.vala"
	_tmp2_ = _tmp1_;
#line 62 "../src/prefs.vala"
	_tmp3_ = _tmp2_;
#line 62 "../src/prefs.vala"
	_tmp5_ = (NULL == _tmp3_) ? 0 : g_quark_from_string (_tmp3_);
#line 62 "../src/prefs.vala"
	if (_tmp5_ == ((0 != _tmp4_label0) ? _tmp4_label0 : (_tmp4_label0 = g_quark_from_static_string ("'small'")))) {
#line 62 "../src/prefs.vala"
		switch (0) {
#line 292 "prefs.c"
			default:
			{
				GtkCheckButton* _tmp6_;
#line 64 "../src/prefs.vala"
				_tmp6_ = self->priv->sml;
#line 64 "../src/prefs.vala"
				gtk_check_button_set_active (_tmp6_, TRUE);
#line 65 "../src/prefs.vala"
				break;
#line 302 "prefs.c"
			}
		}
	} else if (_tmp5_ == ((0 != _tmp4_label1) ? _tmp4_label1 : (_tmp4_label1 = g_quark_from_static_string ("'large'")))) {
#line 62 "../src/prefs.vala"
		switch (0) {
#line 308 "prefs.c"
			default:
			{
				GtkCheckButton* _tmp7_;
#line 71 "../src/prefs.vala"
				_tmp7_ = self->priv->big;
#line 71 "../src/prefs.vala"
				gtk_check_button_set_active (_tmp7_, TRUE);
#line 72 "../src/prefs.vala"
				break;
#line 318 "prefs.c"
			}
		}
	} else {
#line 62 "../src/prefs.vala"
		switch (0) {
#line 324 "prefs.c"
			default:
			{
				GtkCheckButton* _tmp8_;
#line 68 "../src/prefs.vala"
				_tmp8_ = self->priv->mid;
#line 68 "../src/prefs.vala"
				gtk_check_button_set_active (_tmp8_, TRUE);
#line 69 "../src/prefs.vala"
				break;
#line 334 "prefs.c"
			}
		}
	}
}

static void
___lambda7__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
#line 61 "../src/prefs.vala"
	__lambda7_ (self);
#line 347 "prefs.c"
}

EnigmaPreferences*
enigma_preferences_construct (GType object_type,
                              EnigmaMainWindow* win)
{
	EnigmaPreferences * self = NULL;
	Block1Data* _data1_;
	EnigmaSettings* _tmp0_;
	EnigmaSettings* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GQuark _tmp6_ = 0U;
#line 40 "../src/prefs.vala"
	static GQuark _tmp5_label0 = 0;
#line 40 "../src/prefs.vala"
	static GQuark _tmp5_label1 = 0;
#line 366 "prefs.c"
	GtkCheckButton* _tmp10_;
	GtkCheckButton* _tmp11_;
	GtkCheckButton* _tmp12_;
	EnigmaSettings* _tmp13_;
	EnigmaSettings* _tmp14_;
	GSettings* _tmp15_;
	GtkSwitch* _tmp16_;
	EnigmaSettings* _tmp17_;
	GSettings* _tmp18_;
	GtkSwitch* _tmp19_;
	EnigmaSettings* _tmp20_;
	GSettings* _tmp21_;
	GtkSwitch* _tmp22_;
#line 36 "../src/prefs.vala"
	g_return_val_if_fail (win != NULL, NULL);
#line 36 "../src/prefs.vala"
	_data1_ = g_slice_new0 (Block1Data);
#line 36 "../src/prefs.vala"
	_data1_->_ref_count_ = 1;
#line 37 "../src/prefs.vala"
	self = (EnigmaPreferences*) g_object_new (object_type, "parent", win, NULL);
#line 37 "../src/prefs.vala"
	_data1_->self = g_object_ref (self);
#line 38 "../src/prefs.vala"
	_tmp0_ = enigma_settings_new ();
#line 38 "../src/prefs.vala"
	_data1_->settings = _tmp0_;
#line 40 "../src/prefs.vala"
	_tmp1_ = _data1_->settings;
#line 40 "../src/prefs.vala"
	_tmp2_ = enigma_settings_get_font_size (_tmp1_);
#line 40 "../src/prefs.vala"
	_tmp3_ = _tmp2_;
#line 40 "../src/prefs.vala"
	_tmp4_ = _tmp3_;
#line 40 "../src/prefs.vala"
	_tmp6_ = (NULL == _tmp4_) ? 0 : g_quark_from_string (_tmp4_);
#line 40 "../src/prefs.vala"
	if (_tmp6_ == ((0 != _tmp5_label0) ? _tmp5_label0 : (_tmp5_label0 = g_quark_from_static_string ("'small'")))) {
#line 40 "../src/prefs.vala"
		switch (0) {
#line 408 "prefs.c"
			default:
			{
				GtkCheckButton* _tmp7_;
#line 42 "../src/prefs.vala"
				_tmp7_ = self->priv->sml;
#line 42 "../src/prefs.vala"
				gtk_check_button_set_active (_tmp7_, TRUE);
#line 43 "../src/prefs.vala"
				break;
#line 418 "prefs.c"
			}
		}
	} else if (_tmp6_ == ((0 != _tmp5_label1) ? _tmp5_label1 : (_tmp5_label1 = g_quark_from_static_string ("'large'")))) {
#line 40 "../src/prefs.vala"
		switch (0) {
#line 424 "prefs.c"
			default:
			{
				GtkCheckButton* _tmp8_;
#line 49 "../src/prefs.vala"
				_tmp8_ = self->priv->big;
#line 49 "../src/prefs.vala"
				gtk_check_button_set_active (_tmp8_, TRUE);
#line 50 "../src/prefs.vala"
				break;
#line 434 "prefs.c"
			}
		}
	} else {
#line 40 "../src/prefs.vala"
		switch (0) {
#line 440 "prefs.c"
			default:
			{
				GtkCheckButton* _tmp9_;
#line 46 "../src/prefs.vala"
				_tmp9_ = self->priv->mid;
#line 46 "../src/prefs.vala"
				gtk_check_button_set_active (_tmp9_, TRUE);
#line 47 "../src/prefs.vala"
				break;
#line 450 "prefs.c"
			}
		}
	}
#line 52 "../src/prefs.vala"
	_tmp10_ = self->priv->sml;
#line 52 "../src/prefs.vala"
	g_signal_connect_data ((GObject*) _tmp10_, "notify::active", (GCallback) ___lambda4__g_object_notify, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 55 "../src/prefs.vala"
	_tmp11_ = self->priv->mid;
#line 55 "../src/prefs.vala"
	g_signal_connect_data ((GObject*) _tmp11_, "notify::active", (GCallback) ___lambda5__g_object_notify, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 58 "../src/prefs.vala"
	_tmp12_ = self->priv->big;
#line 58 "../src/prefs.vala"
	g_signal_connect_data ((GObject*) _tmp12_, "notify::active", (GCallback) ___lambda6__g_object_notify, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 61 "../src/prefs.vala"
	_tmp13_ = _data1_->settings;
#line 61 "../src/prefs.vala"
	g_signal_connect_data ((GObject*) _tmp13_, "notify::font-size", (GCallback) ___lambda7__g_object_notify, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 76 "../src/prefs.vala"
	_tmp14_ = _data1_->settings;
#line 76 "../src/prefs.vala"
	_tmp15_ = _tmp14_->settings;
#line 76 "../src/prefs.vala"
	_tmp16_ = self->priv->sn;
#line 76 "../src/prefs.vala"
	g_settings_bind (_tmp15_, "show-line-numbers", (GObject*) _tmp16_, "active", G_SETTINGS_BIND_DEFAULT);
#line 77 "../src/prefs.vala"
	_tmp17_ = _data1_->settings;
#line 77 "../src/prefs.vala"
	_tmp18_ = _tmp17_->settings;
#line 77 "../src/prefs.vala"
	_tmp19_ = self->priv->hcl;
#line 77 "../src/prefs.vala"
	g_settings_bind (_tmp18_, "hilight-curr-line", (GObject*) _tmp19_, "active", G_SETTINGS_BIND_DEFAULT);
#line 78 "../src/prefs.vala"
	_tmp20_ = _data1_->settings;
#line 78 "../src/prefs.vala"
	_tmp21_ = _tmp20_->settings;
#line 78 "../src/prefs.vala"
	_tmp22_ = self->priv->hmb;
#line 78 "../src/prefs.vala"
	g_settings_bind (_tmp21_, "hilight-brackets", (GObject*) _tmp22_, "active", G_SETTINGS_BIND_DEFAULT);
#line 36 "../src/prefs.vala"
	block1_data_unref (_data1_);
#line 36 "../src/prefs.vala"
	_data1_ = NULL;
#line 36 "../src/prefs.vala"
	return self;
#line 500 "prefs.c"
}

EnigmaPreferences*
enigma_preferences_new (EnigmaMainWindow* win)
{
#line 36 "../src/prefs.vala"
	return enigma_preferences_construct (ENIGMA_TYPE_PREFERENCES, win);
#line 508 "prefs.c"
}

static void
enigma_preferences_class_init (EnigmaPreferencesClass * klass,
                               gpointer klass_data)
{
#line 22 "../src/prefs.vala"
	enigma_preferences_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/prefs.vala"
	g_type_class_adjust_private_offset (klass, &EnigmaPreferences_private_offset);
#line 22 "../src/prefs.vala"
	G_OBJECT_CLASS (klass)->finalize = enigma_preferences_finalize;
#line 22 "../src/prefs.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/co/tauos/Enigma/prefs.ui");
#line 22 "../src/prefs.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "sml", FALSE, EnigmaPreferences_private_offset + G_STRUCT_OFFSET (EnigmaPreferencesPrivate, sml));
#line 22 "../src/prefs.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "mid", FALSE, EnigmaPreferences_private_offset + G_STRUCT_OFFSET (EnigmaPreferencesPrivate, mid));
#line 22 "../src/prefs.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "big", FALSE, EnigmaPreferences_private_offset + G_STRUCT_OFFSET (EnigmaPreferencesPrivate, big));
#line 22 "../src/prefs.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "sn", FALSE, EnigmaPreferences_private_offset + G_STRUCT_OFFSET (EnigmaPreferencesPrivate, sn));
#line 22 "../src/prefs.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "hcl", FALSE, EnigmaPreferences_private_offset + G_STRUCT_OFFSET (EnigmaPreferencesPrivate, hcl));
#line 22 "../src/prefs.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "hmb", FALSE, EnigmaPreferences_private_offset + G_STRUCT_OFFSET (EnigmaPreferencesPrivate, hmb));
#line 535 "prefs.c"
}

static void
enigma_preferences_instance_init (EnigmaPreferences * self,
                                  gpointer klass)
{
#line 22 "../src/prefs.vala"
	self->priv = enigma_preferences_get_instance_private (self);
#line 22 "../src/prefs.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 546 "prefs.c"
}

static void
enigma_preferences_finalize (GObject * obj)
{
	EnigmaPreferences * self;
#line 22 "../src/prefs.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENIGMA_TYPE_PREFERENCES, EnigmaPreferences);
#line 22 "../src/prefs.vala"
	G_OBJECT_CLASS (enigma_preferences_parent_class)->finalize (obj);
#line 557 "prefs.c"
}

 G_GNUC_NO_INLINE static GType
enigma_preferences_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (EnigmaPreferencesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) enigma_preferences_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EnigmaPreferences), 0, (GInstanceInitFunc) enigma_preferences_instance_init, NULL };
	GType enigma_preferences_type_id;
	enigma_preferences_type_id = g_type_register_static (HE_TYPE_SETTINGS_WINDOW, "EnigmaPreferences", &g_define_type_info, 0);
	EnigmaPreferences_private_offset = g_type_add_instance_private (enigma_preferences_type_id, sizeof (EnigmaPreferencesPrivate));
	return enigma_preferences_type_id;
}

GType
enigma_preferences_get_type (void)
{
	static gsize enigma_preferences_type_id__once = 0;
	if (g_once_init_enter (&enigma_preferences_type_id__once)) {
		GType enigma_preferences_type_id;
		enigma_preferences_type_id = enigma_preferences_get_type_once ();
		g_once_init_leave (&enigma_preferences_type_id__once, enigma_preferences_type_id);
	}
	return enigma_preferences_type_id__once;
}

