/* settings.c generated by valac 0.56.3, the Vala compiler
 * generated from settings.vala, do not modify */

/*
* Copyright (C) 2022 Fyra Labs
*
* This program is free software; you can redistribute it &&/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*/

#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define ENIGMA_TYPE_SETTINGS (enigma_settings_get_type ())
#define ENIGMA_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_SETTINGS, EnigmaSettings))
#define ENIGMA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_SETTINGS, EnigmaSettingsClass))
#define ENIGMA_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_SETTINGS))
#define ENIGMA_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_SETTINGS))
#define ENIGMA_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_SETTINGS, EnigmaSettingsClass))

typedef struct _EnigmaSettings EnigmaSettings;
typedef struct _EnigmaSettingsClass EnigmaSettingsClass;
typedef struct _EnigmaSettingsPrivate EnigmaSettingsPrivate;
enum  {
	ENIGMA_SETTINGS_0_PROPERTY,
	ENIGMA_SETTINGS_FONT_SIZE_PROPERTY,
	ENIGMA_SETTINGS_NUM_PROPERTIES
};
static GParamSpec* enigma_settings_properties[ENIGMA_SETTINGS_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _EnigmaSettings {
	GObject parent_instance;
	EnigmaSettingsPrivate * priv;
	GSettings* settings;
};

struct _EnigmaSettingsClass {
	GObjectClass parent_class;
};

struct _EnigmaSettingsPrivate {
	gchar* _font_size;
};

static gint EnigmaSettings_private_offset;
static gpointer enigma_settings_parent_class = NULL;

VALA_EXTERN GType enigma_settings_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaSettings, g_object_unref)
VALA_EXTERN GAction* enigma_settings_create_action (EnigmaSettings* self,
                                        const gchar* key);
VALA_EXTERN EnigmaSettings* enigma_settings_new (void);
VALA_EXTERN EnigmaSettings* enigma_settings_construct (GType object_type);
VALA_EXTERN const gchar* enigma_settings_get_font_size (EnigmaSettings* self);
VALA_EXTERN void enigma_settings_set_font_size (EnigmaSettings* self,
                                    const gchar* value);
static GObject * enigma_settings_constructor (GType type,
                                       guint n_construct_properties,
                                       GObjectConstructParam * construct_properties);
static void enigma_settings_finalize (GObject * obj);
static GType enigma_settings_get_type_once (void);
static void _vala_enigma_settings_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec);
static void _vala_enigma_settings_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec);

static inline gpointer
enigma_settings_get_instance_private (EnigmaSettings* self)
{
	return G_STRUCT_MEMBER_P (self, EnigmaSettings_private_offset);
}

GAction*
enigma_settings_create_action (EnigmaSettings* self,
                               const gchar* key)
{
	GSettings* _tmp0_;
	GAction* _tmp1_;
	GAction* result;
#line 28 "../src/settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 28 "../src/settings.vala"
	g_return_val_if_fail (key != NULL, NULL);
#line 29 "../src/settings.vala"
	_tmp0_ = self->settings;
#line 29 "../src/settings.vala"
	_tmp1_ = g_settings_create_action (_tmp0_, key);
#line 29 "../src/settings.vala"
	result = _tmp1_;
#line 29 "../src/settings.vala"
	return result;
#line 124 "settings.c"
}

EnigmaSettings*
enigma_settings_construct (GType object_type)
{
	EnigmaSettings * self = NULL;
#line 20 "../src/settings.vala"
	self = (EnigmaSettings*) g_object_new (object_type, NULL);
#line 20 "../src/settings.vala"
	return self;
#line 135 "settings.c"
}

EnigmaSettings*
enigma_settings_new (void)
{
#line 20 "../src/settings.vala"
	return enigma_settings_construct (ENIGMA_TYPE_SETTINGS);
#line 143 "settings.c"
}

const gchar*
enigma_settings_get_font_size (EnigmaSettings* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 22 "../src/settings.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "../src/settings.vala"
	_tmp0_ = self->priv->_font_size;
#line 22 "../src/settings.vala"
	result = _tmp0_;
#line 22 "../src/settings.vala"
	return result;
#line 159 "settings.c"
}

void
enigma_settings_set_font_size (EnigmaSettings* self,
                               const gchar* value)
{
	gchar* old_value;
#line 22 "../src/settings.vala"
	g_return_if_fail (self != NULL);
#line 22 "../src/settings.vala"
	old_value = enigma_settings_get_font_size (self);
#line 22 "../src/settings.vala"
	if (g_strcmp0 (value, old_value) != 0) {
#line 173 "settings.c"
		gchar* _tmp0_;
#line 22 "../src/settings.vala"
		_tmp0_ = g_strdup (value);
#line 22 "../src/settings.vala"
		_g_free0 (self->priv->_font_size);
#line 22 "../src/settings.vala"
		self->priv->_font_size = _tmp0_;
#line 22 "../src/settings.vala"
		g_object_notify_by_pspec ((GObject *) self, enigma_settings_properties[ENIGMA_SETTINGS_FONT_SIZE_PROPERTY]);
#line 183 "settings.c"
	}
}

static GObject *
enigma_settings_constructor (GType type,
                             guint n_construct_properties,
                             GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
#line 24 "../src/settings.vala"
	static GObject * EnigmaSettings_singleton__ref = NULL;
#line 24 "../src/settings.vala"
	static GMutex EnigmaSettings_singleton__lock;
#line 24 "../src/settings.vala"
	static gsize EnigmaSettings_singleton__once = 0;
#line 200 "settings.c"
	EnigmaSettings * self;
	GSettings* _tmp0_;
#line 24 "../src/settings.vala"
	if (g_once_init_enter (&EnigmaSettings_singleton__once)) {
#line 205 "settings.c"
		g_mutex_init (&EnigmaSettings_singleton__lock);
		g_once_init_leave (&EnigmaSettings_singleton__once, 42);
	}
#line 24 "../src/settings.vala"
	g_mutex_lock (&EnigmaSettings_singleton__lock);
#line 24 "../src/settings.vala"
	if (EnigmaSettings_singleton__ref != NULL) {
#line 213 "settings.c"
		g_object_ref (EnigmaSettings_singleton__ref);
		g_mutex_unlock (&EnigmaSettings_singleton__lock);
		return EnigmaSettings_singleton__ref;
	}
#line 24 "../src/settings.vala"
	parent_class = G_OBJECT_CLASS (enigma_settings_parent_class);
#line 24 "../src/settings.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 24 "../src/settings.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENIGMA_TYPE_SETTINGS, EnigmaSettings);
#line 25 "../src/settings.vala"
	_tmp0_ = self->settings;
#line 25 "../src/settings.vala"
	g_settings_bind (_tmp0_, "font-size", (GObject*) self, "font-size", G_SETTINGS_BIND_DEFAULT);
#line 24 "../src/settings.vala"
	EnigmaSettings_singleton__ref = obj;
#line 24 "../src/settings.vala"
	g_object_add_weak_pointer (EnigmaSettings_singleton__ref, (gpointer) (&EnigmaSettings_singleton__ref));
#line 24 "../src/settings.vala"
	g_mutex_unlock (&EnigmaSettings_singleton__lock);
#line 24 "../src/settings.vala"
	return obj;
#line 236 "settings.c"
}

static void
enigma_settings_class_init (EnigmaSettingsClass * klass,
                            gpointer klass_data)
{
#line 20 "../src/settings.vala"
	enigma_settings_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/settings.vala"
	g_type_class_adjust_private_offset (klass, &EnigmaSettings_private_offset);
#line 20 "../src/settings.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_enigma_settings_get_property;
#line 20 "../src/settings.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_enigma_settings_set_property;
#line 20 "../src/settings.vala"
	G_OBJECT_CLASS (klass)->constructor = enigma_settings_constructor;
#line 20 "../src/settings.vala"
	G_OBJECT_CLASS (klass)->finalize = enigma_settings_finalize;
#line 20 "../src/settings.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENIGMA_SETTINGS_FONT_SIZE_PROPERTY, enigma_settings_properties[ENIGMA_SETTINGS_FONT_SIZE_PROPERTY] = g_param_spec_string ("font-size", "font-size", "font-size", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 257 "settings.c"
}

static void
enigma_settings_instance_init (EnigmaSettings * self,
                               gpointer klass)
{
	GSettings* _tmp0_;
#line 20 "../src/settings.vala"
	self->priv = enigma_settings_get_instance_private (self);
#line 21 "../src/settings.vala"
	_tmp0_ = g_settings_new ("co.tauos.Enigma");
#line 21 "../src/settings.vala"
	self->settings = _tmp0_;
#line 271 "settings.c"
}

static void
enigma_settings_finalize (GObject * obj)
{
	EnigmaSettings * self;
#line 20 "../src/settings.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENIGMA_TYPE_SETTINGS, EnigmaSettings);
#line 21 "../src/settings.vala"
	_g_object_unref0 (self->settings);
#line 22 "../src/settings.vala"
	_g_free0 (self->priv->_font_size);
#line 20 "../src/settings.vala"
	G_OBJECT_CLASS (enigma_settings_parent_class)->finalize (obj);
#line 286 "settings.c"
}

 G_GNUC_NO_INLINE static GType
enigma_settings_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (EnigmaSettingsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) enigma_settings_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EnigmaSettings), 0, (GInstanceInitFunc) enigma_settings_instance_init, NULL };
	GType enigma_settings_type_id;
	enigma_settings_type_id = g_type_register_static (G_TYPE_OBJECT, "EnigmaSettings", &g_define_type_info, 0);
	EnigmaSettings_private_offset = g_type_add_instance_private (enigma_settings_type_id, sizeof (EnigmaSettingsPrivate));
	return enigma_settings_type_id;
}

GType
enigma_settings_get_type (void)
{
	static gsize enigma_settings_type_id__once = 0;
	if (g_once_init_enter (&enigma_settings_type_id__once)) {
		GType enigma_settings_type_id;
		enigma_settings_type_id = enigma_settings_get_type_once ();
		g_once_init_leave (&enigma_settings_type_id__once, enigma_settings_type_id);
	}
	return enigma_settings_type_id__once;
}

static void
_vala_enigma_settings_get_property (GObject * object,
                                    guint property_id,
                                    GValue * value,
                                    GParamSpec * pspec)
{
	EnigmaSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENIGMA_TYPE_SETTINGS, EnigmaSettings);
#line 20 "../src/settings.vala"
	switch (property_id) {
#line 20 "../src/settings.vala"
		case ENIGMA_SETTINGS_FONT_SIZE_PROPERTY:
#line 20 "../src/settings.vala"
		g_value_set_string (value, enigma_settings_get_font_size (self));
#line 20 "../src/settings.vala"
		break;
#line 327 "settings.c"
		default:
#line 20 "../src/settings.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/settings.vala"
		break;
#line 333 "settings.c"
	}
}

static void
_vala_enigma_settings_set_property (GObject * object,
                                    guint property_id,
                                    const GValue * value,
                                    GParamSpec * pspec)
{
	EnigmaSettings * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENIGMA_TYPE_SETTINGS, EnigmaSettings);
#line 20 "../src/settings.vala"
	switch (property_id) {
#line 20 "../src/settings.vala"
		case ENIGMA_SETTINGS_FONT_SIZE_PROPERTY:
#line 20 "../src/settings.vala"
		enigma_settings_set_font_size (self, g_value_get_string (value));
#line 20 "../src/settings.vala"
		break;
#line 353 "settings.c"
		default:
#line 20 "../src/settings.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/settings.vala"
		break;
#line 359 "settings.c"
	}
}

