/* window.c generated by valac 0.56.3, the Vala compiler
 * generated from window.vala, do not modify */

/*
* Copyright (c) 2022 Fyra Labs
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public
* License as published by the Free Software Foundation; either
* version 3 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* General Public License for more details.
*
* You should have received a copy of the GNU General Public
* License along with this program; if not, write to the
* Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
* Boston, MA 02110-1301 USA
*
*/

#include <libhelium-1.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gtksourceview/gtksource.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <gio/gio.h>
#include <gee.h>
#include "config.h"
#include <glib/gi18n-lib.h>
#include <glib/gstdio.h>
#include <gdk/gdk.h>

#define ENIGMA_MAIN_WINDOW_ACTION_PREFIX "win."
#define ENIGMA_MAIN_WINDOW_ACTION_ABOUT "action_about"
#define ENIGMA_MAIN_WINDOW_ACTION_PREFS "action_prefs"
#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define ENIGMA_TYPE_MAIN_WINDOW (enigma_main_window_get_type ())
#define ENIGMA_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindow))
#define ENIGMA_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindowClass))
#define ENIGMA_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_MAIN_WINDOW))
#define ENIGMA_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_MAIN_WINDOW))
#define ENIGMA_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindowClass))

typedef struct _EnigmaMainWindow EnigmaMainWindow;
typedef struct _EnigmaMainWindowClass EnigmaMainWindowClass;
typedef struct _EnigmaMainWindowPrivate EnigmaMainWindowPrivate;
enum  {
	ENIGMA_MAIN_WINDOW_0_PROPERTY,
	ENIGMA_MAIN_WINDOW_FILE_NAME_PROPERTY,
	ENIGMA_MAIN_WINDOW_FILE_NAME_EXT_PROPERTY,
	ENIGMA_MAIN_WINDOW_FILE_LINE_COUNT_PROPERTY,
	ENIGMA_MAIN_WINDOW_MODIFIED_PROPERTY,
	ENIGMA_MAIN_WINDOW_ACTIONS_PROPERTY,
	ENIGMA_MAIN_WINDOW_APP_PROPERTY,
	ENIGMA_MAIN_WINDOW_NUM_PROPERTIES
};
static GParamSpec* enigma_main_window_properties[ENIGMA_MAIN_WINDOW_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _EnigmaMainWindowOpenData EnigmaMainWindowOpenData;
typedef struct _EnigmaMainWindowSaveData EnigmaMainWindowSaveData;
#define _g_match_info_unref0(var) ((var == NULL) ? NULL : (var = (g_match_info_unref (var), NULL)))

#define ENIGMA_TYPE_PREFERENCES (enigma_preferences_get_type ())
#define ENIGMA_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_PREFERENCES, EnigmaPreferences))
#define ENIGMA_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_PREFERENCES, EnigmaPreferencesClass))
#define ENIGMA_IS_PREFERENCES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_PREFERENCES))
#define ENIGMA_IS_PREFERENCES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_PREFERENCES))
#define ENIGMA_PREFERENCES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_PREFERENCES, EnigmaPreferencesClass))

typedef struct _EnigmaPreferences EnigmaPreferences;
typedef struct _EnigmaPreferencesClass EnigmaPreferencesClass;
typedef void (*EnigmaMainWindowHookFunc) (gpointer user_data);

#define ENIGMA_TYPE_SETTINGS (enigma_settings_get_type ())
#define ENIGMA_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ENIGMA_TYPE_SETTINGS, EnigmaSettings))
#define ENIGMA_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ENIGMA_TYPE_SETTINGS, EnigmaSettingsClass))
#define ENIGMA_IS_SETTINGS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ENIGMA_TYPE_SETTINGS))
#define ENIGMA_IS_SETTINGS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ENIGMA_TYPE_SETTINGS))
#define ENIGMA_SETTINGS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ENIGMA_TYPE_SETTINGS, EnigmaSettingsClass))

typedef struct _EnigmaSettings EnigmaSettings;
typedef struct _EnigmaSettingsClass EnigmaSettingsClass;
typedef struct _Block3Data Block3Data;
typedef struct _EnigmaSettingsPrivate EnigmaSettingsPrivate;
enum  {
	ENIGMA_MAIN_WINDOW_CLICKED_SIGNAL,
	ENIGMA_MAIN_WINDOW_NUM_SIGNALS
};
static guint enigma_main_window_signals[ENIGMA_MAIN_WINDOW_NUM_SIGNALS] = {0};

struct _EnigmaMainWindow {
	HeApplicationWindow parent_instance;
	EnigmaMainWindowPrivate * priv;
};

struct _EnigmaMainWindowClass {
	HeApplicationWindowClass parent_class;
};

struct _EnigmaMainWindowPrivate {
	GtkMenuButton* menu_button;
	GtkButton* new_button;
	GtkButton* open_button;
	GtkButton* save_as_button;
	GtkSourceView* text_box;
	GtkSearchEntry* search_entry;
	gchar* _file_name;
	gchar* _file_name_ext;
	gchar* _file_line_count;
	gboolean _modified;
	GSimpleActionGroup* _actions;
	HeApplication* _app;
};

struct _EnigmaMainWindowOpenData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	EnigmaMainWindow* self;
	GFile* file;
	GFile* _tmp0_;
	gchar* file_path;
	gchar* _tmp1_;
	gchar* text;
	gchar* _tmp2_;
	gboolean _tmp3_;
	GtkSourceView* _tmp4_;
	GtkTextBuffer* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	GtkSourceView* _tmp16_;
	GtkTextBuffer* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	GError* err;
	GError* _tmp22_;
	const gchar* _tmp23_;
	GError* _inner_error0_;
};

struct _EnigmaMainWindowSaveData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GTask* _async_result;
	EnigmaMainWindow* self;
	GFile* file;
	GFile* _tmp0_;
	GtkTextIter start;
	GtkTextIter end;
	GtkSourceView* _tmp1_;
	GtkTextBuffer* _tmp2_;
	GtkTextIter _tmp3_;
	GtkTextIter _tmp4_;
	gchar* _tmp5_;
	gchar* _tmp6_;
	GtkSourceView* _tmp7_;
	GtkTextBuffer* _tmp8_;
	GtkTextIter _tmp9_;
	GtkTextIter _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	gchar* _tmp19_;
	gchar* _tmp20_;
	gchar* _tmp21_;
	gchar* _tmp22_;
	GError* err;
	GError* _tmp23_;
	const gchar* _tmp24_;
	GError* _inner_error0_;
};

struct _Block3Data {
	int _ref_count_;
	EnigmaMainWindow* self;
	EnigmaSettings* settings;
};

struct _EnigmaSettings {
	GObject parent_instance;
	EnigmaSettingsPrivate * priv;
	GSettings* settings;
};

struct _EnigmaSettingsClass {
	GObjectClass parent_class;
};

static gint EnigmaMainWindow_private_offset;
static gpointer enigma_main_window_parent_class = NULL;
VALA_EXTERN GeeMultiMap* enigma_main_window_action_accelerators;
GeeMultiMap* enigma_main_window_action_accelerators = NULL;

VALA_EXTERN GType enigma_main_window_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaMainWindow, g_object_unref)
VALA_EXTERN void enigma_main_window_action_about (EnigmaMainWindow* self);
static void _enigma_main_window_action_about_gsimple_action_activate_callback (GSimpleAction* action,
                                                                        GVariant* parameter,
                                                                        gpointer self);
VALA_EXTERN void enigma_main_window_action_prefs (EnigmaMainWindow* self);
static void _enigma_main_window_action_prefs_gsimple_action_activate_callback (GSimpleAction* action,
                                                                        GVariant* parameter,
                                                                        gpointer self);
VALA_EXTERN EnigmaMainWindow* enigma_main_window_new (HeApplication* application);
VALA_EXTERN EnigmaMainWindow* enigma_main_window_construct (GType object_type,
                                                HeApplication* application);
VALA_EXTERN void enigma_main_window_on_search_activate (EnigmaMainWindow* self);
static void _enigma_main_window_on_search_activate_gtk_search_entry_search_changed (GtkSearchEntry* _sender,
                                                                             gpointer self);
VALA_EXTERN void enigma_main_window_on_new_button_clicked (EnigmaMainWindow* self);
VALA_EXTERN void enigma_main_window_set_file_name (EnigmaMainWindow* self,
                                       const gchar* value);
VALA_EXTERN void enigma_main_window_set_file_name_ext (EnigmaMainWindow* self,
                                           const gchar* value);
VALA_EXTERN void enigma_main_window_set_file_line_count (EnigmaMainWindow* self,
                                             const gchar* value);
VALA_EXTERN gint enigma_main_window_get_lines (EnigmaMainWindow* self);
VALA_EXTERN void enigma_main_window_set_modified (EnigmaMainWindow* self,
                                      gboolean value);
static void enigma_main_window_open_data_free (gpointer _data);
VALA_EXTERN void enigma_main_window_open (EnigmaMainWindow* self,
                              GAsyncReadyCallback _callback_,
                              gpointer _user_data_);
VALA_EXTERN void enigma_main_window_open_finish (EnigmaMainWindow* self,
                                     GAsyncResult* _res_);
static gboolean enigma_main_window_open_co (EnigmaMainWindowOpenData* _data_);
VALA_EXTERN void enigma_utils_display_open_dialog (GAsyncReadyCallback _callback_,
                                       gpointer _user_data_);
VALA_EXTERN GFile* enigma_utils_display_open_dialog_finish (GAsyncResult* _res_);
static void enigma_main_window_open_ready (GObject* source_object,
                                    GAsyncResult* _res_,
                                    gpointer _user_data_);
static void enigma_main_window_save_data_free (gpointer _data);
VALA_EXTERN void enigma_main_window_save (EnigmaMainWindow* self,
                              GAsyncReadyCallback _callback_,
                              gpointer _user_data_);
VALA_EXTERN void enigma_main_window_save_finish (EnigmaMainWindow* self,
                                     GAsyncResult* _res_);
static gboolean enigma_main_window_save_co (EnigmaMainWindowSaveData* _data_);
VALA_EXTERN void enigma_utils_display_save_dialog (GAsyncReadyCallback _callback_,
                                       gpointer _user_data_);
VALA_EXTERN GFile* enigma_utils_display_save_dialog_finish (GAsyncResult* _res_);
static void enigma_main_window_save_ready (GObject* source_object,
                                    GAsyncResult* _res_,
                                    gpointer _user_data_);
VALA_EXTERN void enigma_main_window_on_text_box_changed (EnigmaMainWindow* self);
VALA_EXTERN GType enigma_preferences_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaPreferences, g_object_unref)
VALA_EXTERN EnigmaPreferences* enigma_preferences_new (EnigmaMainWindow* win);
VALA_EXTERN EnigmaPreferences* enigma_preferences_construct (GType object_type,
                                                 EnigmaMainWindow* win);
VALA_EXTERN void enigma_main_window_load (EnigmaMainWindow* self,
                              GFile* file);
VALA_EXTERN const gchar* enigma_main_window_get_file_name (EnigmaMainWindow* self);
VALA_EXTERN const gchar* enigma_main_window_get_file_name_ext (EnigmaMainWindow* self);
VALA_EXTERN const gchar* enigma_main_window_get_file_line_count (EnigmaMainWindow* self);
VALA_EXTERN gboolean enigma_main_window_get_modified (EnigmaMainWindow* self);
VALA_EXTERN GSimpleActionGroup* enigma_main_window_get_actions (EnigmaMainWindow* self);
static void enigma_main_window_set_actions (EnigmaMainWindow* self,
                                     GSimpleActionGroup* value);
VALA_EXTERN HeApplication* enigma_main_window_get_app (EnigmaMainWindow* self);
static void enigma_main_window_set_app (EnigmaMainWindow* self,
                                 HeApplication* value);
static GObject * enigma_main_window_constructor (GType type,
                                          guint n_construct_properties,
                                          GObjectConstructParam * construct_properties);
VALA_EXTERN GType enigma_settings_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (EnigmaSettings, g_object_unref)
static Block3Data* block3_data_ref (Block3Data* _data3_);
static void block3_data_unref (void * _userdata_);
static void _vala_array_add1 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void _enigma_main_window___lambda9_ (EnigmaMainWindow* self);
static void __enigma_main_window___lambda9__gtk_button_clicked (GtkButton* _sender,
                                                         gpointer self);
static void _enigma_main_window___lambda10_ (EnigmaMainWindow* self);
static void __enigma_main_window___lambda10__gtk_button_clicked (GtkButton* _sender,
                                                          gpointer self);
static void _enigma_main_window___lambda11_ (EnigmaMainWindow* self);
static void __enigma_main_window___lambda11__gtk_button_clicked (GtkButton* _sender,
                                                          gpointer self);
static void _enigma_main_window___lambda12_ (EnigmaMainWindow* self);
static void __enigma_main_window___lambda12__gtk_text_buffer_changed (GtkTextBuffer* _sender,
                                                               gpointer self);
static gboolean _enigma_main_window___lambda13_ (EnigmaMainWindow* self);
static gboolean __enigma_main_window___lambda13__gsource_func (gpointer self);
VALA_EXTERN EnigmaSettings* enigma_settings_new (void);
VALA_EXTERN EnigmaSettings* enigma_settings_construct (GType object_type);
VALA_EXTERN const gchar* enigma_settings_get_font_size (EnigmaSettings* self);
static void _enigma_main_window___lambda14_ (Block3Data* _data3_);
static void __enigma_main_window___lambda14__g_object_notify (GObject* _sender,
                                                       GParamSpec* pspec,
                                                       gpointer self);
static void enigma_main_window_finalize (GObject * obj);
static GType enigma_main_window_get_type_once (void);
static void _vala_enigma_main_window_get_property (GObject * object,
                                            guint property_id,
                                            GValue * value,
                                            GParamSpec * pspec);
static void _vala_enigma_main_window_set_property (GObject * object,
                                            guint property_id,
                                            const GValue * value,
                                            GParamSpec * pspec);
static void _vala_array_destroy (gpointer array,
                          gssize array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gssize array_length,
                       GDestroyNotify destroy_func);

static const GActionEntry ENIGMA_MAIN_WINDOW_ACTION_ENTRIES[2] = {{ENIGMA_MAIN_WINDOW_ACTION_ABOUT, _enigma_main_window_action_about_gsimple_action_activate_callback}, {ENIGMA_MAIN_WINDOW_ACTION_PREFS, _enigma_main_window_action_prefs_gsimple_action_activate_callback}};

static inline gpointer
enigma_main_window_get_instance_private (EnigmaMainWindow* self)
{
	return G_STRUCT_MEMBER_P (self, EnigmaMainWindow_private_offset);
}

static void
_enigma_main_window_action_about_gsimple_action_activate_callback (GSimpleAction* action,
                                                                   GVariant* parameter,
                                                                   gpointer self)
{
#line 77 "../src/window.vala"
	enigma_main_window_action_about ((EnigmaMainWindow*) self);
#line 363 "window.c"
}

static void
_enigma_main_window_action_prefs_gsimple_action_activate_callback (GSimpleAction* action,
                                                                   GVariant* parameter,
                                                                   gpointer self)
{
#line 77 "../src/window.vala"
	enigma_main_window_action_prefs ((EnigmaMainWindow*) self);
#line 373 "window.c"
}

EnigmaMainWindow*
enigma_main_window_construct (GType object_type,
                              HeApplication* application)
{
	EnigmaMainWindow * self = NULL;
#line 83 "../src/window.vala"
	g_return_val_if_fail (application != NULL, NULL);
#line 84 "../src/window.vala"
	self = (EnigmaMainWindow*) g_object_new (object_type, "application", application, "app", application, "icon-name", APP_ID, "title", "Enigma", NULL);
#line 83 "../src/window.vala"
	return self;
#line 387 "window.c"
}

EnigmaMainWindow*
enigma_main_window_new (HeApplication* application)
{
#line 83 "../src/window.vala"
	return enigma_main_window_construct (ENIGMA_TYPE_MAIN_WINDOW, application);
#line 395 "window.c"
}

void
enigma_main_window_on_search_activate (EnigmaMainWindow* self)
{
	gchar* search_str = NULL;
	GtkSearchEntry* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	GtkTextIter start_iter = {0};
	GtkTextIter end_iter = {0};
	GtkTextIter match_start = {0};
	GtkTextIter match_end = {0};
	GtkSourceView* _tmp3_;
	GtkTextBuffer* _tmp4_;
	GtkTextIter _tmp5_ = {0};
	GtkTextIter _tmp6_ = {0};
	gboolean found = FALSE;
	const gchar* _tmp7_;
	GtkTextIter _tmp8_;
	GtkTextIter _tmp9_ = {0};
	GtkTextIter _tmp10_ = {0};
	gboolean _tmp11_;
#line 179 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 180 "../src/window.vala"
	_tmp0_ = self->priv->search_entry;
#line 180 "../src/window.vala"
	_tmp1_ = gtk_editable_get_text ((GtkEditable*) _tmp0_);
#line 180 "../src/window.vala"
	_tmp2_ = g_strdup (_tmp1_);
#line 180 "../src/window.vala"
	search_str = _tmp2_;
#line 182 "../src/window.vala"
	_tmp3_ = self->priv->text_box;
#line 182 "../src/window.vala"
	_tmp4_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp3_);
#line 182 "../src/window.vala"
	gtk_text_buffer_get_bounds (_tmp4_, &_tmp5_, &_tmp6_);
#line 182 "../src/window.vala"
	start_iter = _tmp5_;
#line 182 "../src/window.vala"
	end_iter = _tmp6_;
#line 183 "../src/window.vala"
	_tmp7_ = search_str;
#line 183 "../src/window.vala"
	_tmp8_ = end_iter;
#line 183 "../src/window.vala"
	_tmp11_ = gtk_text_iter_forward_search (&start_iter, _tmp7_, 0, &_tmp9_, &_tmp10_, &_tmp8_);
#line 183 "../src/window.vala"
	match_start = _tmp9_;
#line 183 "../src/window.vala"
	match_end = _tmp10_;
#line 183 "../src/window.vala"
	found = _tmp11_;
#line 184 "../src/window.vala"
	if (found) {
#line 453 "window.c"
		GtkSourceView* _tmp12_;
		GtkTextBuffer* _tmp13_;
		GtkTextIter _tmp14_;
		GtkTextIter _tmp15_;
#line 185 "../src/window.vala"
		_tmp12_ = self->priv->text_box;
#line 185 "../src/window.vala"
		_tmp13_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp12_);
#line 185 "../src/window.vala"
		_tmp14_ = match_start;
#line 185 "../src/window.vala"
		_tmp15_ = match_end;
#line 185 "../src/window.vala"
		gtk_text_buffer_select_range (_tmp13_, &_tmp14_, &_tmp15_);
#line 468 "window.c"
	}
#line 179 "../src/window.vala"
	_g_free0 (search_str);
#line 472 "window.c"
}

static void
_enigma_main_window_on_search_activate_gtk_search_entry_search_changed (GtkSearchEntry* _sender,
                                                                        gpointer self)
{
#line 22 "../src/window.vala"
	enigma_main_window_on_search_activate ((EnigmaMainWindow*) self);
#line 481 "window.c"
}

void
enigma_main_window_on_new_button_clicked (EnigmaMainWindow* self)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
#line 189 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 190 "../src/window.vala"
	enigma_main_window_set_file_name (self, NULL);
#line 191 "../src/window.vala"
	enigma_main_window_set_file_name_ext (self, NULL);
#line 192 "../src/window.vala"
	enigma_main_window_set_file_line_count (self, NULL);
#line 193 "../src/window.vala"
	enigma_main_window_set_file_name (self, "New File");
#line 194 "../src/window.vala"
	enigma_main_window_set_file_name_ext (self, "new_file.txt");
#line 195 "../src/window.vala"
	_tmp0_ = g_strdup_printf ("%d", enigma_main_window_get_lines (self));
#line 195 "../src/window.vala"
	_tmp1_ = _tmp0_;
#line 195 "../src/window.vala"
	_tmp2_ = g_strconcat (_tmp1_, _ (" lines"), NULL);
#line 195 "../src/window.vala"
	_tmp3_ = _tmp2_;
#line 195 "../src/window.vala"
	enigma_main_window_set_file_line_count (self, _tmp3_);
#line 195 "../src/window.vala"
	_g_free0 (_tmp3_);
#line 195 "../src/window.vala"
	_g_free0 (_tmp1_);
#line 196 "../src/window.vala"
	enigma_main_window_set_modified (self, FALSE);
#line 519 "window.c"
}

static void
enigma_main_window_open_data_free (gpointer _data)
{
	EnigmaMainWindowOpenData* _data_;
	_data_ = _data;
#line 22 "../src/window.vala"
	_g_object_unref0 (_data_->self);
#line 22 "../src/window.vala"
	g_slice_free (EnigmaMainWindowOpenData, _data_);
#line 531 "window.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 22 "../src/window.vala"
	return self ? g_object_ref (self) : NULL;
#line 539 "window.c"
}

void
enigma_main_window_open (EnigmaMainWindow* self,
                         GAsyncReadyCallback _callback_,
                         gpointer _user_data_)
{
	EnigmaMainWindowOpenData* _data_;
	EnigmaMainWindow* _tmp0_;
#line 22 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 22 "../src/window.vala"
	_data_ = g_slice_new0 (EnigmaMainWindowOpenData);
#line 22 "../src/window.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 22 "../src/window.vala"
	g_task_set_task_data (_data_->_async_result, _data_, enigma_main_window_open_data_free);
#line 22 "../src/window.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 22 "../src/window.vala"
	_data_->self = _tmp0_;
#line 22 "../src/window.vala"
	enigma_main_window_open_co (_data_);
#line 563 "window.c"
}

void
enigma_main_window_open_finish (EnigmaMainWindow* self,
                                GAsyncResult* _res_)
{
	EnigmaMainWindowOpenData* _data_;
#line 22 "../src/window.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 573 "window.c"
}

static void
enigma_main_window_open_ready (GObject* source_object,
                               GAsyncResult* _res_,
                               gpointer _user_data_)
{
	EnigmaMainWindowOpenData* _data_;
#line 200 "../src/window.vala"
	_data_ = _user_data_;
#line 200 "../src/window.vala"
	_data_->_source_object_ = source_object;
#line 200 "../src/window.vala"
	_data_->_res_ = _res_;
#line 200 "../src/window.vala"
	enigma_main_window_open_co (_data_);
#line 590 "window.c"
}

static gchar*
string_replace (const gchar* self,
                const gchar* old,
                const gchar* replacement)
{
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	GError* _inner_error0_ = NULL;
	gchar* result;
#line 1542 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1542 "glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1542 "glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 1543 "glib-2.0.vapi"
	if ((*((gchar*) self)) == '\0') {
#line 1543 "glib-2.0.vapi"
		_tmp1_ = TRUE;
#line 612 "window.c"
	} else {
#line 1543 "glib-2.0.vapi"
		_tmp1_ = (*((gchar*) old)) == '\0';
#line 616 "window.c"
	}
#line 1543 "glib-2.0.vapi"
	if (_tmp1_) {
#line 1543 "glib-2.0.vapi"
		_tmp0_ = TRUE;
#line 622 "window.c"
	} else {
#line 1543 "glib-2.0.vapi"
		_tmp0_ = g_strcmp0 (old, replacement) == 0;
#line 626 "window.c"
	}
#line 1543 "glib-2.0.vapi"
	if (_tmp0_) {
#line 630 "window.c"
		gchar* _tmp2_;
#line 1544 "glib-2.0.vapi"
		_tmp2_ = g_strdup (self);
#line 1544 "glib-2.0.vapi"
		result = _tmp2_;
#line 1544 "glib-2.0.vapi"
		return result;
#line 638 "window.c"
	}
	{
		GRegex* regex = NULL;
		gchar* _tmp3_;
		gchar* _tmp4_;
		GRegex* _tmp5_;
		GRegex* _tmp6_;
		gchar* _tmp7_ = NULL;
		GRegex* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
#line 1547 "glib-2.0.vapi"
		_tmp3_ = g_regex_escape_string (old, -1);
#line 1547 "glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1547 "glib-2.0.vapi"
		_tmp5_ = g_regex_new (_tmp4_, 0, 0, &_inner_error0_);
#line 1547 "glib-2.0.vapi"
		_tmp6_ = _tmp5_;
#line 1547 "glib-2.0.vapi"
		_g_free0 (_tmp4_);
#line 1547 "glib-2.0.vapi"
		regex = _tmp6_;
#line 1547 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1547 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 666 "window.c"
				goto __catch0_g_regex_error;
			}
#line 1547 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1547 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1547 "glib-2.0.vapi"
			return NULL;
#line 675 "window.c"
		}
#line 1548 "glib-2.0.vapi"
		_tmp8_ = regex;
#line 1548 "glib-2.0.vapi"
		_tmp9_ = g_regex_replace_literal (_tmp8_, self, (gssize) -1, 0, replacement, 0, &_inner_error0_);
#line 1548 "glib-2.0.vapi"
		_tmp7_ = _tmp9_;
#line 1548 "glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1548 "glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1548 "glib-2.0.vapi"
			if (_inner_error0_->domain == G_REGEX_ERROR) {
#line 689 "window.c"
				goto __catch0_g_regex_error;
			}
#line 1548 "glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1548 "glib-2.0.vapi"
			g_clear_error (&_inner_error0_);
#line 1548 "glib-2.0.vapi"
			return NULL;
#line 698 "window.c"
		}
#line 1548 "glib-2.0.vapi"
		_tmp10_ = _tmp7_;
#line 1548 "glib-2.0.vapi"
		_tmp7_ = NULL;
#line 1548 "glib-2.0.vapi"
		result = _tmp10_;
#line 1548 "glib-2.0.vapi"
		_g_free0 (_tmp7_);
#line 1548 "glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1548 "glib-2.0.vapi"
		return result;
#line 712 "window.c"
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
#line 1546 "glib-2.0.vapi"
		g_clear_error (&_inner_error0_);
#line 1550 "glib-2.0.vapi"
		g_assert_not_reached ();
#line 721 "window.c"
	}
	__finally0:
#line 1546 "glib-2.0.vapi"
	g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 1546 "glib-2.0.vapi"
	g_clear_error (&_inner_error0_);
#line 1546 "glib-2.0.vapi"
	return NULL;
#line 730 "window.c"
}

static gboolean
enigma_main_window_open_co (EnigmaMainWindowOpenData* _data_)
{
#line 199 "../src/window.vala"
	switch (_data_->_state_) {
#line 199 "../src/window.vala"
		case 0:
#line 740 "window.c"
		goto _state_0;
#line 199 "../src/window.vala"
		case 1:
#line 744 "window.c"
		goto _state_1;
		default:
#line 199 "../src/window.vala"
		g_assert_not_reached ();
#line 749 "window.c"
	}
	_state_0:
#line 200 "../src/window.vala"
	_data_->_state_ = 1;
#line 200 "../src/window.vala"
	enigma_utils_display_open_dialog (enigma_main_window_open_ready, _data_);
#line 200 "../src/window.vala"
	return FALSE;
#line 758 "window.c"
	_state_1:
#line 200 "../src/window.vala"
	_data_->_tmp0_ = enigma_utils_display_open_dialog_finish (_data_->_res_);
#line 200 "../src/window.vala"
	_data_->file = _data_->_tmp0_;
#line 201 "../src/window.vala"
	_data_->_tmp1_ = g_file_get_path (_data_->file);
#line 201 "../src/window.vala"
	_data_->file_path = _data_->_tmp1_;
#line 768 "window.c"
	{
#line 204 "../src/window.vala"
		_data_->_tmp2_ = NULL;
#line 204 "../src/window.vala"
		g_file_get_contents (_data_->file_path, &_data_->_tmp2_, NULL, &_data_->_inner_error0_);
#line 204 "../src/window.vala"
		_g_free0 (_data_->text);
#line 204 "../src/window.vala"
		_data_->text = _data_->_tmp2_;
#line 204 "../src/window.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 780 "window.c"
			goto __catch0_g_error;
		}
#line 205 "../src/window.vala"
		if (_data_->file != NULL) {
#line 205 "../src/window.vala"
			_data_->_tmp3_ = _data_->text != NULL;
#line 787 "window.c"
		} else {
#line 205 "../src/window.vala"
			_data_->_tmp3_ = FALSE;
#line 791 "window.c"
		}
#line 205 "../src/window.vala"
		if (_data_->_tmp3_) {
#line 206 "../src/window.vala"
			_data_->_tmp4_ = _data_->self->priv->text_box;
#line 206 "../src/window.vala"
			_data_->_tmp5_ = gtk_text_view_get_buffer ((GtkTextView*) _data_->_tmp4_);
#line 206 "../src/window.vala"
			gtk_text_buffer_set_text (_data_->_tmp5_, _data_->text, -1);
#line 207 "../src/window.vala"
			_data_->_tmp6_ = g_file_get_basename (_data_->file);
#line 207 "../src/window.vala"
			_data_->_tmp7_ = _data_->_tmp6_;
#line 207 "../src/window.vala"
			_data_->_tmp8_ = string_replace (_data_->_tmp7_, ".txt", "");
#line 207 "../src/window.vala"
			_data_->_tmp9_ = _data_->_tmp8_;
#line 207 "../src/window.vala"
			enigma_main_window_set_file_name (_data_->self, _data_->_tmp9_);
#line 207 "../src/window.vala"
			_g_free0 (_data_->_tmp9_);
#line 207 "../src/window.vala"
			_g_free0 (_data_->_tmp7_);
#line 208 "../src/window.vala"
			_data_->_tmp10_ = g_file_get_basename (_data_->file);
#line 208 "../src/window.vala"
			_data_->_tmp11_ = _data_->_tmp10_;
#line 208 "../src/window.vala"
			enigma_main_window_set_file_name_ext (_data_->self, _data_->_tmp11_);
#line 208 "../src/window.vala"
			_g_free0 (_data_->_tmp11_);
#line 209 "../src/window.vala"
			_data_->_tmp12_ = g_strdup_printf ("%d", enigma_main_window_get_lines (_data_->self));
#line 209 "../src/window.vala"
			_data_->_tmp13_ = _data_->_tmp12_;
#line 209 "../src/window.vala"
			_data_->_tmp14_ = g_strconcat (_data_->_tmp13_, _ (" lines"), NULL);
#line 209 "../src/window.vala"
			_data_->_tmp15_ = _data_->_tmp14_;
#line 209 "../src/window.vala"
			enigma_main_window_set_file_line_count (_data_->self, _data_->_tmp15_);
#line 209 "../src/window.vala"
			_g_free0 (_data_->_tmp15_);
#line 209 "../src/window.vala"
			_g_free0 (_data_->_tmp13_);
#line 837 "window.c"
		} else {
#line 211 "../src/window.vala"
			_data_->_tmp16_ = _data_->self->priv->text_box;
#line 211 "../src/window.vala"
			_data_->_tmp17_ = gtk_text_view_get_buffer ((GtkTextView*) _data_->_tmp16_);
#line 211 "../src/window.vala"
			gtk_text_buffer_set_text (_data_->_tmp17_, "", -1);
#line 212 "../src/window.vala"
			enigma_main_window_set_file_name (_data_->self, "New File");
#line 213 "../src/window.vala"
			enigma_main_window_set_file_name_ext (_data_->self, "new_file.txt");
#line 214 "../src/window.vala"
			_data_->_tmp18_ = g_strdup_printf ("%d", enigma_main_window_get_lines (_data_->self));
#line 214 "../src/window.vala"
			_data_->_tmp19_ = _data_->_tmp18_;
#line 214 "../src/window.vala"
			_data_->_tmp20_ = g_strconcat (_data_->_tmp19_, _ (" lines"), NULL);
#line 214 "../src/window.vala"
			_data_->_tmp21_ = _data_->_tmp20_;
#line 214 "../src/window.vala"
			enigma_main_window_set_file_line_count (_data_->self, _data_->_tmp21_);
#line 214 "../src/window.vala"
			_g_free0 (_data_->_tmp21_);
#line 214 "../src/window.vala"
			_g_free0 (_data_->_tmp19_);
#line 863 "window.c"
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 203 "../src/window.vala"
		_data_->err = _data_->_inner_error0_;
#line 203 "../src/window.vala"
		_data_->_inner_error0_ = NULL;
#line 217 "../src/window.vala"
		_data_->_tmp22_ = _data_->err;
#line 217 "../src/window.vala"
		_data_->_tmp23_ = _data_->_tmp22_->message;
#line 217 "../src/window.vala"
		g_print ("%s", _data_->_tmp23_);
#line 203 "../src/window.vala"
		_g_error_free0 (_data_->err);
#line 881 "window.c"
	}
	__finally0:
#line 203 "../src/window.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 203 "../src/window.vala"
		_g_free0 (_data_->text);
#line 203 "../src/window.vala"
		_g_free0 (_data_->file_path);
#line 203 "../src/window.vala"
		_g_object_unref0 (_data_->file);
#line 203 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 203 "../src/window.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 203 "../src/window.vala"
		g_object_unref (_data_->_async_result);
#line 203 "../src/window.vala"
		return FALSE;
#line 900 "window.c"
	}
#line 199 "../src/window.vala"
	_g_free0 (_data_->text);
#line 199 "../src/window.vala"
	_g_free0 (_data_->file_path);
#line 199 "../src/window.vala"
	_g_object_unref0 (_data_->file);
#line 199 "../src/window.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 199 "../src/window.vala"
	if (_data_->_state_ != 0) {
#line 199 "../src/window.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 199 "../src/window.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 916 "window.c"
		}
	}
#line 199 "../src/window.vala"
	g_object_unref (_data_->_async_result);
#line 199 "../src/window.vala"
	return FALSE;
#line 923 "window.c"
}

static void
enigma_main_window_save_data_free (gpointer _data)
{
	EnigmaMainWindowSaveData* _data_;
	_data_ = _data;
#line 22 "../src/window.vala"
	_g_object_unref0 (_data_->self);
#line 22 "../src/window.vala"
	g_slice_free (EnigmaMainWindowSaveData, _data_);
#line 935 "window.c"
}

void
enigma_main_window_save (EnigmaMainWindow* self,
                         GAsyncReadyCallback _callback_,
                         gpointer _user_data_)
{
	EnigmaMainWindowSaveData* _data_;
	EnigmaMainWindow* _tmp0_;
#line 22 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 22 "../src/window.vala"
	_data_ = g_slice_new0 (EnigmaMainWindowSaveData);
#line 22 "../src/window.vala"
	_data_->_async_result = g_task_new (G_OBJECT (self), NULL, _callback_, _user_data_);
#line 22 "../src/window.vala"
	g_task_set_task_data (_data_->_async_result, _data_, enigma_main_window_save_data_free);
#line 22 "../src/window.vala"
	_tmp0_ = _g_object_ref0 (self);
#line 22 "../src/window.vala"
	_data_->self = _tmp0_;
#line 22 "../src/window.vala"
	enigma_main_window_save_co (_data_);
#line 959 "window.c"
}

void
enigma_main_window_save_finish (EnigmaMainWindow* self,
                                GAsyncResult* _res_)
{
	EnigmaMainWindowSaveData* _data_;
#line 22 "../src/window.vala"
	_data_ = g_task_propagate_pointer (G_TASK (_res_), NULL);
#line 969 "window.c"
}

static void
enigma_main_window_save_ready (GObject* source_object,
                               GAsyncResult* _res_,
                               gpointer _user_data_)
{
	EnigmaMainWindowSaveData* _data_;
#line 222 "../src/window.vala"
	_data_ = _user_data_;
#line 222 "../src/window.vala"
	_data_->_source_object_ = source_object;
#line 222 "../src/window.vala"
	_data_->_res_ = _res_;
#line 222 "../src/window.vala"
	enigma_main_window_save_co (_data_);
#line 986 "window.c"
}

static gboolean
enigma_main_window_save_co (EnigmaMainWindowSaveData* _data_)
{
#line 221 "../src/window.vala"
	switch (_data_->_state_) {
#line 221 "../src/window.vala"
		case 0:
#line 996 "window.c"
		goto _state_0;
#line 221 "../src/window.vala"
		case 1:
#line 1000 "window.c"
		goto _state_1;
		default:
#line 221 "../src/window.vala"
		g_assert_not_reached ();
#line 1005 "window.c"
	}
	_state_0:
#line 222 "../src/window.vala"
	_data_->_state_ = 1;
#line 222 "../src/window.vala"
	enigma_utils_display_save_dialog (enigma_main_window_save_ready, _data_);
#line 222 "../src/window.vala"
	return FALSE;
#line 1014 "window.c"
	_state_1:
#line 222 "../src/window.vala"
	_data_->_tmp0_ = enigma_utils_display_save_dialog_finish (_data_->_res_);
#line 222 "../src/window.vala"
	_data_->file = _data_->_tmp0_;
#line 224 "../src/window.vala"
	_data_->_tmp1_ = _data_->self->priv->text_box;
#line 224 "../src/window.vala"
	_data_->_tmp2_ = gtk_text_view_get_buffer ((GtkTextView*) _data_->_tmp1_);
#line 224 "../src/window.vala"
	memset (&_data_->_tmp3_, 0, sizeof (GtkTextIter));
#line 224 "../src/window.vala"
	memset (&_data_->_tmp4_, 0, sizeof (GtkTextIter));
#line 224 "../src/window.vala"
	gtk_text_buffer_get_bounds (_data_->_tmp2_, &_data_->_tmp3_, &_data_->_tmp4_);
#line 224 "../src/window.vala"
	_data_->start = _data_->_tmp3_;
#line 224 "../src/window.vala"
	_data_->end = _data_->_tmp4_;
#line 1034 "window.c"
	{
#line 226 "../src/window.vala"
		_data_->_tmp5_ = g_file_get_path (_data_->file);
#line 226 "../src/window.vala"
		_data_->_tmp6_ = _data_->_tmp5_;
#line 226 "../src/window.vala"
		_data_->_tmp7_ = _data_->self->priv->text_box;
#line 226 "../src/window.vala"
		_data_->_tmp8_ = gtk_text_view_get_buffer ((GtkTextView*) _data_->_tmp7_);
#line 226 "../src/window.vala"
		_data_->_tmp9_ = _data_->start;
#line 226 "../src/window.vala"
		_data_->_tmp10_ = _data_->end;
#line 226 "../src/window.vala"
		_data_->_tmp11_ = gtk_text_buffer_get_text (_data_->_tmp8_, &_data_->_tmp9_, &_data_->_tmp10_, FALSE);
#line 226 "../src/window.vala"
		_data_->_tmp12_ = _data_->_tmp11_;
#line 226 "../src/window.vala"
		g_file_set_contents (_data_->_tmp6_, _data_->_tmp12_, (gssize) -1, &_data_->_inner_error0_);
#line 226 "../src/window.vala"
		_g_free0 (_data_->_tmp12_);
#line 226 "../src/window.vala"
		_g_free0 (_data_->_tmp6_);
#line 226 "../src/window.vala"
		if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 1060 "window.c"
			goto __catch0_g_error;
		}
#line 227 "../src/window.vala"
		_data_->_tmp13_ = g_file_get_basename (_data_->file);
#line 227 "../src/window.vala"
		_data_->_tmp14_ = _data_->_tmp13_;
#line 227 "../src/window.vala"
		_data_->_tmp15_ = string_replace (_data_->_tmp14_, ".txt", "");
#line 227 "../src/window.vala"
		_data_->_tmp16_ = _data_->_tmp15_;
#line 227 "../src/window.vala"
		enigma_main_window_set_file_name (_data_->self, _data_->_tmp16_);
#line 227 "../src/window.vala"
		_g_free0 (_data_->_tmp16_);
#line 227 "../src/window.vala"
		_g_free0 (_data_->_tmp14_);
#line 228 "../src/window.vala"
		_data_->_tmp17_ = g_file_get_basename (_data_->file);
#line 228 "../src/window.vala"
		_data_->_tmp18_ = _data_->_tmp17_;
#line 228 "../src/window.vala"
		enigma_main_window_set_file_name_ext (_data_->self, _data_->_tmp18_);
#line 228 "../src/window.vala"
		_g_free0 (_data_->_tmp18_);
#line 229 "../src/window.vala"
		_data_->_tmp19_ = g_strdup_printf ("%d", enigma_main_window_get_lines (_data_->self));
#line 229 "../src/window.vala"
		_data_->_tmp20_ = _data_->_tmp19_;
#line 229 "../src/window.vala"
		_data_->_tmp21_ = g_strconcat (_data_->_tmp20_, _ (" lines"), NULL);
#line 229 "../src/window.vala"
		_data_->_tmp22_ = _data_->_tmp21_;
#line 229 "../src/window.vala"
		enigma_main_window_set_file_line_count (_data_->self, _data_->_tmp22_);
#line 229 "../src/window.vala"
		_g_free0 (_data_->_tmp22_);
#line 229 "../src/window.vala"
		_g_free0 (_data_->_tmp20_);
#line 230 "../src/window.vala"
		enigma_main_window_set_modified (_data_->self, FALSE);
#line 1101 "window.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
#line 225 "../src/window.vala"
		_data_->err = _data_->_inner_error0_;
#line 225 "../src/window.vala"
		_data_->_inner_error0_ = NULL;
#line 232 "../src/window.vala"
		_data_->_tmp23_ = _data_->err;
#line 232 "../src/window.vala"
		_data_->_tmp24_ = _data_->_tmp23_->message;
#line 232 "../src/window.vala"
		g_print ("%s", _data_->_tmp24_);
#line 225 "../src/window.vala"
		_g_error_free0 (_data_->err);
#line 1118 "window.c"
	}
	__finally0:
#line 225 "../src/window.vala"
	if (G_UNLIKELY (_data_->_inner_error0_ != NULL)) {
#line 225 "../src/window.vala"
		_g_object_unref0 (_data_->file);
#line 225 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error0_->message, g_quark_to_string (_data_->_inner_error0_->domain), _data_->_inner_error0_->code);
#line 225 "../src/window.vala"
		g_clear_error (&_data_->_inner_error0_);
#line 225 "../src/window.vala"
		g_object_unref (_data_->_async_result);
#line 225 "../src/window.vala"
		return FALSE;
#line 1133 "window.c"
	}
#line 221 "../src/window.vala"
	_g_object_unref0 (_data_->file);
#line 221 "../src/window.vala"
	g_task_return_pointer (_data_->_async_result, _data_, NULL);
#line 221 "../src/window.vala"
	if (_data_->_state_ != 0) {
#line 221 "../src/window.vala"
		while (!g_task_get_completed (_data_->_async_result)) {
#line 221 "../src/window.vala"
			g_main_context_iteration (g_task_get_context (_data_->_async_result), TRUE);
#line 1145 "window.c"
		}
	}
#line 221 "../src/window.vala"
	g_object_unref (_data_->_async_result);
#line 221 "../src/window.vala"
	return FALSE;
#line 1152 "window.c"
}

void
enigma_main_window_on_text_box_changed (EnigmaMainWindow* self)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
#line 236 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 237 "../src/window.vala"
	enigma_main_window_set_modified (self, TRUE);
#line 238 "../src/window.vala"
	_tmp0_ = g_strdup_printf ("%d", enigma_main_window_get_lines (self));
#line 238 "../src/window.vala"
	_tmp1_ = _tmp0_;
#line 238 "../src/window.vala"
	_tmp2_ = g_strconcat (_tmp1_, _ (" lines"), NULL);
#line 238 "../src/window.vala"
	_tmp3_ = _tmp2_;
#line 238 "../src/window.vala"
	enigma_main_window_set_file_line_count (self, _tmp3_);
#line 238 "../src/window.vala"
	_g_free0 (_tmp3_);
#line 238 "../src/window.vala"
	_g_free0 (_tmp1_);
#line 1180 "window.c"
}

gint
enigma_main_window_get_lines (EnigmaMainWindow* self)
{
	GtkTextIter start = {0};
	GtkTextIter end = {0};
	GtkSourceView* _tmp0_;
	GtkTextBuffer* _tmp1_;
	GtkTextIter _tmp2_ = {0};
	GtkTextIter _tmp3_ = {0};
	gchar* buffer = NULL;
	GtkSourceView* _tmp4_;
	GtkTextBuffer* _tmp5_;
	GtkTextIter _tmp6_;
	GtkTextIter _tmp7_;
	gchar* _tmp8_;
	gint i = 0;
	gint lines = 0;
	GError* _inner_error0_ = NULL;
	gint result;
#line 241 "../src/window.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 243 "../src/window.vala"
	_tmp0_ = self->priv->text_box;
#line 243 "../src/window.vala"
	_tmp1_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp0_);
#line 243 "../src/window.vala"
	gtk_text_buffer_get_bounds (_tmp1_, &_tmp2_, &_tmp3_);
#line 243 "../src/window.vala"
	start = _tmp2_;
#line 243 "../src/window.vala"
	end = _tmp3_;
#line 244 "../src/window.vala"
	_tmp4_ = self->priv->text_box;
#line 244 "../src/window.vala"
	_tmp5_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp4_);
#line 244 "../src/window.vala"
	_tmp6_ = start;
#line 244 "../src/window.vala"
	_tmp7_ = end;
#line 244 "../src/window.vala"
	_tmp8_ = gtk_text_buffer_get_text (_tmp5_, &_tmp6_, &_tmp7_, FALSE);
#line 244 "../src/window.vala"
	buffer = _tmp8_;
#line 245 "../src/window.vala"
	i = 0;
#line 1228 "window.c"
	{
		GMatchInfo* match = NULL;
		GRegex* reg = NULL;
		GRegex* _tmp9_;
		GRegex* _tmp10_;
		const gchar* _tmp11_;
		GMatchInfo* _tmp12_ = NULL;
		gboolean _tmp13_;
#line 248 "../src/window.vala"
		_tmp9_ = g_regex_new ("(?m)(.*$)", 0, 0, &_inner_error0_);
#line 248 "../src/window.vala"
		reg = _tmp9_;
#line 248 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 248 "../src/window.vala"
			_g_match_info_unref0 (match);
#line 1245 "window.c"
			goto __catch0_g_error;
		}
#line 249 "../src/window.vala"
		_tmp10_ = reg;
#line 249 "../src/window.vala"
		_tmp11_ = buffer;
#line 249 "../src/window.vala"
		_tmp13_ = g_regex_match (_tmp10_, _tmp11_, 0, &_tmp12_);
#line 249 "../src/window.vala"
		_g_match_info_unref0 (match);
#line 249 "../src/window.vala"
		match = _tmp12_;
#line 249 "../src/window.vala"
		if (_tmp13_) {
#line 1260 "window.c"
			{
				gboolean _tmp14_ = FALSE;
#line 250 "../src/window.vala"
				_tmp14_ = TRUE;
#line 250 "../src/window.vala"
				while (TRUE) {
#line 1267 "window.c"
					gint _tmp17_;
#line 250 "../src/window.vala"
					if (!_tmp14_) {
#line 1271 "window.c"
						gboolean _tmp15_ = FALSE;
						GMatchInfo* _tmp16_;
#line 252 "../src/window.vala"
						_tmp16_ = match;
#line 252 "../src/window.vala"
						_tmp15_ = g_match_info_next (_tmp16_, &_inner_error0_);
#line 252 "../src/window.vala"
						if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 252 "../src/window.vala"
							_g_regex_unref0 (reg);
#line 252 "../src/window.vala"
							_g_match_info_unref0 (match);
#line 1284 "window.c"
							goto __catch0_g_error;
						}
#line 252 "../src/window.vala"
						if (!_tmp15_) {
#line 252 "../src/window.vala"
							break;
#line 1291 "window.c"
						}
					}
#line 250 "../src/window.vala"
					_tmp14_ = FALSE;
#line 251 "../src/window.vala"
					_tmp17_ = i;
#line 251 "../src/window.vala"
					i = _tmp17_ + 1;
#line 1300 "window.c"
				}
			}
		}
#line 246 "../src/window.vala"
		_g_regex_unref0 (reg);
#line 246 "../src/window.vala"
		_g_match_info_unref0 (match);
#line 1308 "window.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp18_;
		const gchar* _tmp19_;
#line 246 "../src/window.vala"
		e = _inner_error0_;
#line 246 "../src/window.vala"
		_inner_error0_ = NULL;
#line 255 "../src/window.vala"
		_tmp18_ = e;
#line 255 "../src/window.vala"
		_tmp19_ = _tmp18_->message;
#line 255 "../src/window.vala"
		g_warning ("window.vala:255: %s", _tmp19_);
#line 246 "../src/window.vala"
		_g_error_free0 (e);
#line 1328 "window.c"
	}
	__finally0:
#line 246 "../src/window.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1333 "window.c"
		gint _tmp20_ = -1;
#line 246 "../src/window.vala"
		_g_free0 (buffer);
#line 246 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 246 "../src/window.vala"
		g_clear_error (&_inner_error0_);
#line 246 "../src/window.vala"
		return _tmp20_;
#line 1343 "window.c"
	}
#line 258 "../src/window.vala"
	lines = i / 2;
#line 260 "../src/window.vala"
	result = lines;
#line 260 "../src/window.vala"
	_g_free0 (buffer);
#line 260 "../src/window.vala"
	return result;
#line 1353 "window.c"
}

void
enigma_main_window_action_about (EnigmaMainWindow* self)
{
	HeAboutWindow* about = NULL;
	gchar** _tmp0_;
	gchar** _tmp1_;
	gint _tmp1__length1;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar** _tmp4_;
	gchar** _tmp5_;
	gint _tmp5__length1;
	HeAboutWindow* _tmp6_;
	HeAboutWindow* _tmp7_;
#line 263 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 264 "../src/window.vala"
	_tmp0_ = g_new0 (gchar*, 0 + 1);
#line 264 "../src/window.vala"
	_tmp1_ = _tmp0_;
#line 264 "../src/window.vala"
	_tmp1__length1 = 0;
#line 264 "../src/window.vala"
	_tmp2_ = g_strdup ("Lains");
#line 264 "../src/window.vala"
	_tmp3_ = g_strdup ("Lea");
#line 264 "../src/window.vala"
	_tmp4_ = g_new0 (gchar*, 2 + 1);
#line 264 "../src/window.vala"
	_tmp4_[0] = _tmp2_;
#line 264 "../src/window.vala"
	_tmp4_[1] = _tmp3_;
#line 264 "../src/window.vala"
	_tmp5_ = _tmp4_;
#line 264 "../src/window.vala"
	_tmp5__length1 = 2;
#line 264 "../src/window.vala"
	_tmp6_ = he_about_window_new ((GtkWindow*) self, "Enigma" NAME_SUFFIX, APP_ID, VERSION, APP_ID, "https://github.com/tau-OS/enigma/tree/main/po", "https://github.com/tau-OS/enigma/issues", "catalogue://co.tauos.Enigma", _tmp1_, 0, _tmp5_, 2, 2022, HE_ABOUT_WINDOW_LICENSES_GPLv3, HE_COLORS_BLUE);
#line 264 "../src/window.vala"
	g_object_ref_sink (_tmp6_);
#line 264 "../src/window.vala"
	_tmp7_ = _tmp6_;
#line 264 "../src/window.vala"
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) g_free), NULL);
#line 264 "../src/window.vala"
	_tmp1_ = (_vala_array_free (_tmp1_, _tmp1__length1, (GDestroyNotify) g_free), NULL);
#line 264 "../src/window.vala"
	about = _tmp7_;
#line 279 "../src/window.vala"
	gtk_window_present ((GtkWindow*) about);
#line 263 "../src/window.vala"
	_g_object_unref0 (about);
#line 1408 "window.c"
}

void
enigma_main_window_action_prefs (EnigmaMainWindow* self)
{
	EnigmaPreferences* settings = NULL;
	EnigmaPreferences* _tmp0_;
#line 282 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 283 "../src/window.vala"
	_tmp0_ = enigma_preferences_new (self);
#line 283 "../src/window.vala"
	g_object_ref_sink (_tmp0_);
#line 283 "../src/window.vala"
	settings = _tmp0_;
#line 284 "../src/window.vala"
	he_window_set_parent ((HeWindow*) settings, (GtkWindow*) self);
#line 285 "../src/window.vala"
	gtk_window_present ((GtkWindow*) settings);
#line 282 "../src/window.vala"
	_g_object_unref0 (settings);
#line 1430 "window.c"
}

void
enigma_main_window_load (EnigmaMainWindow* self,
                         GFile* file)
{
	guint8* text = NULL;
	gint text_length1 = 0;
	gint _text_size_ = 0;
	GError* _inner_error0_ = NULL;
#line 288 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 288 "../src/window.vala"
	g_return_if_fail (file != NULL);
#line 1445 "window.c"
	{
		guint8* _tmp0_ = NULL;
		gsize _tmp1_ = 0;
		GtkSourceView* _tmp2_;
		GtkTextBuffer* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		gchar* _tmp6_;
		gchar* _tmp7_;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		gchar* _tmp12_;
		gchar* _tmp13_;
#line 291 "../src/window.vala"
		g_file_load_contents (file, NULL, &_tmp0_, &_tmp1_, NULL, &_inner_error0_);
#line 291 "../src/window.vala"
		text = (g_free (text), NULL);
#line 291 "../src/window.vala"
		text = _tmp0_;
#line 291 "../src/window.vala"
		text_length1 = _tmp1_;
#line 291 "../src/window.vala"
		_text_size_ = text_length1;
#line 291 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 1473 "window.c"
			goto __catch0_g_error;
		}
#line 292 "../src/window.vala"
		_tmp2_ = self->priv->text_box;
#line 292 "../src/window.vala"
		_tmp3_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp2_);
#line 292 "../src/window.vala"
		gtk_text_buffer_set_text (_tmp3_, (const gchar*) text, -1);
#line 293 "../src/window.vala"
		_tmp4_ = g_file_get_basename (file);
#line 293 "../src/window.vala"
		_tmp5_ = _tmp4_;
#line 293 "../src/window.vala"
		_tmp6_ = string_replace (_tmp5_, ".txt", "");
#line 293 "../src/window.vala"
		_tmp7_ = _tmp6_;
#line 293 "../src/window.vala"
		enigma_main_window_set_file_name (self, _tmp7_);
#line 293 "../src/window.vala"
		_g_free0 (_tmp7_);
#line 293 "../src/window.vala"
		_g_free0 (_tmp5_);
#line 294 "../src/window.vala"
		_tmp8_ = g_file_get_basename (file);
#line 294 "../src/window.vala"
		_tmp9_ = _tmp8_;
#line 294 "../src/window.vala"
		enigma_main_window_set_file_name_ext (self, _tmp9_);
#line 294 "../src/window.vala"
		_g_free0 (_tmp9_);
#line 295 "../src/window.vala"
		_tmp10_ = g_strdup_printf ("%d", enigma_main_window_get_lines (self));
#line 295 "../src/window.vala"
		_tmp11_ = _tmp10_;
#line 295 "../src/window.vala"
		_tmp12_ = g_strconcat (_tmp11_, _ (" lines"), NULL);
#line 295 "../src/window.vala"
		_tmp13_ = _tmp12_;
#line 295 "../src/window.vala"
		enigma_main_window_set_file_line_count (self, _tmp13_);
#line 295 "../src/window.vala"
		_g_free0 (_tmp13_);
#line 295 "../src/window.vala"
		_g_free0 (_tmp11_);
#line 1518 "window.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* err = NULL;
		GError* _tmp14_;
		const gchar* _tmp15_;
#line 290 "../src/window.vala"
		err = _inner_error0_;
#line 290 "../src/window.vala"
		_inner_error0_ = NULL;
#line 297 "../src/window.vala"
		_tmp14_ = err;
#line 297 "../src/window.vala"
		_tmp15_ = _tmp14_->message;
#line 297 "../src/window.vala"
		g_print ("%s", _tmp15_);
#line 290 "../src/window.vala"
		_g_error_free0 (err);
#line 1538 "window.c"
	}
	__finally0:
#line 290 "../src/window.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 290 "../src/window.vala"
		text = (g_free (text), NULL);
#line 290 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 290 "../src/window.vala"
		g_clear_error (&_inner_error0_);
#line 290 "../src/window.vala"
		return;
#line 1551 "window.c"
	}
#line 288 "../src/window.vala"
	text = (g_free (text), NULL);
#line 1555 "window.c"
}

const gchar*
enigma_main_window_get_file_name (EnigmaMainWindow* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 41 "../src/window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 41 "../src/window.vala"
	_tmp0_ = self->priv->_file_name;
#line 41 "../src/window.vala"
	result = _tmp0_;
#line 41 "../src/window.vala"
	return result;
#line 1571 "window.c"
}

void
enigma_main_window_set_file_name (EnigmaMainWindow* self,
                                  const gchar* value)
{
	gchar* _tmp0_;
#line 42 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 43 "../src/window.vala"
	_tmp0_ = g_strdup (value);
#line 43 "../src/window.vala"
	_g_free0 (self->priv->_file_name);
#line 43 "../src/window.vala"
	self->priv->_file_name = _tmp0_;
#line 42 "../src/window.vala"
	g_object_notify_by_pspec ((GObject *) self, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_FILE_NAME_PROPERTY]);
#line 1589 "window.c"
}

const gchar*
enigma_main_window_get_file_name_ext (EnigmaMainWindow* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 49 "../src/window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 49 "../src/window.vala"
	_tmp0_ = self->priv->_file_name_ext;
#line 49 "../src/window.vala"
	result = _tmp0_;
#line 49 "../src/window.vala"
	return result;
#line 1605 "window.c"
}

void
enigma_main_window_set_file_name_ext (EnigmaMainWindow* self,
                                      const gchar* value)
{
	gchar* _tmp0_;
#line 50 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 51 "../src/window.vala"
	_tmp0_ = g_strdup (value);
#line 51 "../src/window.vala"
	_g_free0 (self->priv->_file_name_ext);
#line 51 "../src/window.vala"
	self->priv->_file_name_ext = _tmp0_;
#line 50 "../src/window.vala"
	g_object_notify_by_pspec ((GObject *) self, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_FILE_NAME_EXT_PROPERTY]);
#line 1623 "window.c"
}

const gchar*
enigma_main_window_get_file_line_count (EnigmaMainWindow* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 57 "../src/window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 57 "../src/window.vala"
	_tmp0_ = self->priv->_file_line_count;
#line 57 "../src/window.vala"
	result = _tmp0_;
#line 57 "../src/window.vala"
	return result;
#line 1639 "window.c"
}

void
enigma_main_window_set_file_line_count (EnigmaMainWindow* self,
                                        const gchar* value)
{
	gchar* _tmp0_;
#line 58 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 59 "../src/window.vala"
	_tmp0_ = g_strdup (value);
#line 59 "../src/window.vala"
	_g_free0 (self->priv->_file_line_count);
#line 59 "../src/window.vala"
	self->priv->_file_line_count = _tmp0_;
#line 58 "../src/window.vala"
	g_object_notify_by_pspec ((GObject *) self, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_FILE_LINE_COUNT_PROPERTY]);
#line 1657 "window.c"
}

gboolean
enigma_main_window_get_modified (EnigmaMainWindow* self)
{
	gboolean result;
#line 65 "../src/window.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 65 "../src/window.vala"
	result = self->priv->_modified;
#line 65 "../src/window.vala"
	return result;
#line 1670 "window.c"
}

void
enigma_main_window_set_modified (EnigmaMainWindow* self,
                                 gboolean value)
{
#line 66 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 67 "../src/window.vala"
	self->priv->_modified = value;
#line 66 "../src/window.vala"
	g_object_notify_by_pspec ((GObject *) self, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_MODIFIED_PROPERTY]);
#line 1683 "window.c"
}

GSimpleActionGroup*
enigma_main_window_get_actions (EnigmaMainWindow* self)
{
	GSimpleActionGroup* result;
	GSimpleActionGroup* _tmp0_;
#line 71 "../src/window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 71 "../src/window.vala"
	_tmp0_ = self->priv->_actions;
#line 71 "../src/window.vala"
	result = _tmp0_;
#line 71 "../src/window.vala"
	return result;
#line 1699 "window.c"
}

static void
enigma_main_window_set_actions (EnigmaMainWindow* self,
                                GSimpleActionGroup* value)
{
	GSimpleActionGroup* old_value;
#line 71 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 71 "../src/window.vala"
	old_value = enigma_main_window_get_actions (self);
#line 71 "../src/window.vala"
	if (old_value != value) {
#line 1713 "window.c"
		GSimpleActionGroup* _tmp0_;
#line 71 "../src/window.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 71 "../src/window.vala"
		_g_object_unref0 (self->priv->_actions);
#line 71 "../src/window.vala"
		self->priv->_actions = _tmp0_;
#line 71 "../src/window.vala"
		g_object_notify_by_pspec ((GObject *) self, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_ACTIONS_PROPERTY]);
#line 1723 "window.c"
	}
}

HeApplication*
enigma_main_window_get_app (EnigmaMainWindow* self)
{
	HeApplication* result;
	HeApplication* _tmp0_;
#line 82 "../src/window.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 82 "../src/window.vala"
	_tmp0_ = self->priv->_app;
#line 82 "../src/window.vala"
	result = _tmp0_;
#line 82 "../src/window.vala"
	return result;
#line 1740 "window.c"
}

static void
enigma_main_window_set_app (EnigmaMainWindow* self,
                            HeApplication* value)
{
	HeApplication* old_value;
#line 82 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 82 "../src/window.vala"
	old_value = enigma_main_window_get_app (self);
#line 82 "../src/window.vala"
	if (old_value != value) {
#line 1754 "window.c"
		HeApplication* _tmp0_;
#line 82 "../src/window.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 82 "../src/window.vala"
		_g_object_unref0 (self->priv->_app);
#line 82 "../src/window.vala"
		self->priv->_app = _tmp0_;
#line 82 "../src/window.vala"
		g_object_notify_by_pspec ((GObject *) self, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_APP_PROPERTY]);
#line 1764 "window.c"
	}
}

static Block3Data*
block3_data_ref (Block3Data* _data3_)
{
#line 92 "../src/window.vala"
	g_atomic_int_inc (&_data3_->_ref_count_);
#line 92 "../src/window.vala"
	return _data3_;
#line 1775 "window.c"
}

static void
block3_data_unref (void * _userdata_)
{
	Block3Data* _data3_;
	_data3_ = (Block3Data*) _userdata_;
#line 92 "../src/window.vala"
	if (g_atomic_int_dec_and_test (&_data3_->_ref_count_)) {
#line 1785 "window.c"
		EnigmaMainWindow* self;
#line 92 "../src/window.vala"
		self = _data3_->self;
#line 92 "../src/window.vala"
		_g_object_unref0 (_data3_->settings);
#line 92 "../src/window.vala"
		_g_object_unref0 (self);
#line 92 "../src/window.vala"
		g_slice_free (Block3Data, _data3_);
#line 1795 "window.c"
	}
}

static void
_vala_array_add1 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
#line 100 "../src/window.vala"
	if ((*length) == (*size)) {
#line 100 "../src/window.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 100 "../src/window.vala"
		*array = g_renew (gchar*, *array, (*size) + 1);
#line 1811 "window.c"
	}
#line 100 "../src/window.vala"
	(*array)[(*length)++] = value;
#line 100 "../src/window.vala"
	(*array)[*length] = NULL;
#line 1817 "window.c"
}

static void
_enigma_main_window___lambda9_ (EnigmaMainWindow* self)
{
#line 114 "../src/window.vala"
	enigma_main_window_on_new_button_clicked (self);
#line 1825 "window.c"
}

static void
__enigma_main_window___lambda9__gtk_button_clicked (GtkButton* _sender,
                                                    gpointer self)
{
#line 114 "../src/window.vala"
	_enigma_main_window___lambda9_ ((EnigmaMainWindow*) self);
#line 1834 "window.c"
}

static void
_enigma_main_window___lambda10_ (EnigmaMainWindow* self)
{
#line 115 "../src/window.vala"
	enigma_main_window_open (self, NULL, NULL);
#line 1842 "window.c"
}

static void
__enigma_main_window___lambda10__gtk_button_clicked (GtkButton* _sender,
                                                     gpointer self)
{
#line 115 "../src/window.vala"
	_enigma_main_window___lambda10_ ((EnigmaMainWindow*) self);
#line 1851 "window.c"
}

static void
_enigma_main_window___lambda11_ (EnigmaMainWindow* self)
{
#line 116 "../src/window.vala"
	enigma_main_window_save (self, NULL, NULL);
#line 1859 "window.c"
}

static void
__enigma_main_window___lambda11__gtk_button_clicked (GtkButton* _sender,
                                                     gpointer self)
{
#line 116 "../src/window.vala"
	_enigma_main_window___lambda11_ ((EnigmaMainWindow*) self);
#line 1868 "window.c"
}

static void
_enigma_main_window___lambda12_ (EnigmaMainWindow* self)
{
#line 117 "../src/window.vala"
	enigma_main_window_on_text_box_changed (self);
#line 1876 "window.c"
}

static void
__enigma_main_window___lambda12__gtk_text_buffer_changed (GtkTextBuffer* _sender,
                                                          gpointer self)
{
#line 117 "../src/window.vala"
	_enigma_main_window___lambda12_ ((EnigmaMainWindow*) self);
#line 1885 "window.c"
}

static gboolean
_enigma_main_window___lambda13_ (EnigmaMainWindow* self)
{
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gboolean result;
#line 124 "../src/window.vala"
	_tmp0_ = g_strdup_printf ("%d", enigma_main_window_get_lines (self));
#line 124 "../src/window.vala"
	_tmp1_ = _tmp0_;
#line 124 "../src/window.vala"
	_tmp2_ = g_strconcat (_tmp1_, _ (" lines"), NULL);
#line 124 "../src/window.vala"
	_tmp3_ = _tmp2_;
#line 124 "../src/window.vala"
	enigma_main_window_set_file_line_count (self, _tmp3_);
#line 124 "../src/window.vala"
	_g_free0 (_tmp3_);
#line 124 "../src/window.vala"
	_g_free0 (_tmp1_);
#line 125 "../src/window.vala"
	result = TRUE;
#line 125 "../src/window.vala"
	return result;
#line 1914 "window.c"
}

static gboolean
__enigma_main_window___lambda13__gsource_func (gpointer self)
{
	gboolean result;
	result = _enigma_main_window___lambda13_ ((EnigmaMainWindow*) self);
#line 123 "../src/window.vala"
	return result;
#line 1924 "window.c"
}

static void
_enigma_main_window___lambda14_ (Block3Data* _data3_)
{
	EnigmaMainWindow* self;
	EnigmaSettings* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	GQuark _tmp5_ = 0U;
#line 149 "../src/window.vala"
	static GQuark _tmp4_label0 = 0;
#line 149 "../src/window.vala"
	static GQuark _tmp4_label1 = 0;
#line 148 "../src/window.vala"
	self = _data3_->self;
#line 149 "../src/window.vala"
	_tmp0_ = _data3_->settings;
#line 149 "../src/window.vala"
	_tmp1_ = enigma_settings_get_font_size (_tmp0_);
#line 149 "../src/window.vala"
	_tmp2_ = _tmp1_;
#line 149 "../src/window.vala"
	_tmp3_ = _tmp2_;
#line 149 "../src/window.vala"
	_tmp5_ = (NULL == _tmp3_) ? 0 : g_quark_from_string (_tmp3_);
#line 149 "../src/window.vala"
	if (_tmp5_ == ((0 != _tmp4_label0) ? _tmp4_label0 : (_tmp4_label0 = g_quark_from_static_string ("'small'")))) {
#line 149 "../src/window.vala"
		switch (0) {
#line 1956 "window.c"
			default:
			{
				GtkSourceView* _tmp6_;
				GtkSourceView* _tmp7_;
				GtkSourceView* _tmp8_;
#line 151 "../src/window.vala"
				_tmp6_ = self->priv->text_box;
#line 151 "../src/window.vala"
				gtk_widget_add_css_class ((GtkWidget*) _tmp6_, "sml-font");
#line 152 "../src/window.vala"
				_tmp7_ = self->priv->text_box;
#line 152 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp7_, "med-font");
#line 153 "../src/window.vala"
				_tmp8_ = self->priv->text_box;
#line 153 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp8_, "big-font");
#line 154 "../src/window.vala"
				break;
#line 1976 "window.c"
			}
		}
	} else if (_tmp5_ == ((0 != _tmp4_label1) ? _tmp4_label1 : (_tmp4_label1 = g_quark_from_static_string ("'large'")))) {
#line 149 "../src/window.vala"
		switch (0) {
#line 1982 "window.c"
			default:
			{
				GtkSourceView* _tmp9_;
				GtkSourceView* _tmp10_;
				GtkSourceView* _tmp11_;
#line 162 "../src/window.vala"
				_tmp9_ = self->priv->text_box;
#line 162 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp9_, "sml-font");
#line 163 "../src/window.vala"
				_tmp10_ = self->priv->text_box;
#line 163 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp10_, "med-font");
#line 164 "../src/window.vala"
				_tmp11_ = self->priv->text_box;
#line 164 "../src/window.vala"
				gtk_widget_add_css_class ((GtkWidget*) _tmp11_, "big-font");
#line 165 "../src/window.vala"
				break;
#line 2002 "window.c"
			}
		}
	} else {
#line 149 "../src/window.vala"
		switch (0) {
#line 2008 "window.c"
			default:
			{
				GtkSourceView* _tmp12_;
				GtkSourceView* _tmp13_;
				GtkSourceView* _tmp14_;
#line 157 "../src/window.vala"
				_tmp12_ = self->priv->text_box;
#line 157 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp12_, "sml-font");
#line 158 "../src/window.vala"
				_tmp13_ = self->priv->text_box;
#line 158 "../src/window.vala"
				gtk_widget_add_css_class ((GtkWidget*) _tmp13_, "med-font");
#line 159 "../src/window.vala"
				_tmp14_ = self->priv->text_box;
#line 159 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp14_, "big-font");
#line 160 "../src/window.vala"
				break;
#line 2028 "window.c"
			}
		}
	}
}

static void
__enigma_main_window___lambda14__g_object_notify (GObject* _sender,
                                                  GParamSpec* pspec,
                                                  gpointer self)
{
#line 148 "../src/window.vala"
	_enigma_main_window___lambda14_ (self);
#line 2041 "window.c"
}

static GObject *
enigma_main_window_constructor (GType type,
                                guint n_construct_properties,
                                GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	EnigmaMainWindow * self;
	Block3Data* _data3_;
	GSimpleActionGroup* _tmp0_;
	GSimpleActionGroup* _tmp1_;
	GSimpleActionGroup* _tmp2_;
	GSimpleActionGroup* _tmp3_;
	HeApplication* _tmp24_;
	gchar* _tmp25_;
	gchar** _tmp26_;
	gchar** _tmp27_;
	gint _tmp27__length1;
	GtkBuilder* builder = NULL;
	GtkBuilder* _tmp28_;
	GtkMenuButton* _tmp29_;
	GtkBuilder* _tmp30_;
	GObject* _tmp31_;
	GtkIconTheme* theme = NULL;
	GdkDisplay* _tmp32_;
	GtkIconTheme* _tmp33_;
	GtkIconTheme* _tmp34_;
	GtkIconTheme* _tmp35_;
	GtkButton* _tmp36_;
	GtkButton* _tmp37_;
	GtkButton* _tmp38_;
	GtkSourceView* _tmp39_;
	GtkTextBuffer* _tmp40_;
	gchar* _tmp41_;
	gchar* _tmp42_;
	gchar* _tmp43_;
	gchar* _tmp44_;
	EnigmaSettings* _tmp45_;
	EnigmaSettings* _tmp46_;
	const gchar* _tmp47_;
	const gchar* _tmp48_;
	const gchar* _tmp49_;
	GQuark _tmp51_ = 0U;
#line 130 "../src/window.vala"
	static GQuark _tmp50_label0 = 0;
#line 130 "../src/window.vala"
	static GQuark _tmp50_label1 = 0;
#line 2091 "window.c"
	EnigmaSettings* _tmp61_;
	EnigmaSettings* _tmp62_;
	GSettings* _tmp63_;
	GtkSourceView* _tmp64_;
	EnigmaSettings* _tmp65_;
	GSettings* _tmp66_;
	GtkSourceView* _tmp67_;
	EnigmaSettings* _tmp68_;
	GSettings* _tmp69_;
	GtkSourceView* _tmp70_;
	GtkTextBuffer* _tmp71_;
#line 92 "../src/window.vala"
	parent_class = G_OBJECT_CLASS (enigma_main_window_parent_class);
#line 92 "../src/window.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 92 "../src/window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindow);
#line 92 "../src/window.vala"
	_data3_ = g_slice_new0 (Block3Data);
#line 92 "../src/window.vala"
	_data3_->_ref_count_ = 1;
#line 92 "../src/window.vala"
	_data3_->self = g_object_ref (self);
#line 94 "../src/window.vala"
	_tmp0_ = g_simple_action_group_new ();
#line 94 "../src/window.vala"
	_tmp1_ = _tmp0_;
#line 94 "../src/window.vala"
	enigma_main_window_set_actions (self, _tmp1_);
#line 94 "../src/window.vala"
	_g_object_unref0 (_tmp1_);
#line 95 "../src/window.vala"
	_tmp2_ = self->priv->_actions;
#line 95 "../src/window.vala"
	g_action_map_add_action_entries ((GActionMap*) _tmp2_, ENIGMA_MAIN_WINDOW_ACTION_ENTRIES, (gint) G_N_ELEMENTS (ENIGMA_MAIN_WINDOW_ACTION_ENTRIES), self);
#line 96 "../src/window.vala"
	_tmp3_ = self->priv->_actions;
#line 96 "../src/window.vala"
	gtk_widget_insert_action_group ((GtkWidget*) self, "win", (GActionGroup*) _tmp3_);
#line 2131 "window.c"
	{
		GeeIterator* _action_it = NULL;
		GeeMultiMap* _tmp4_;
		GeeSet* _tmp5_;
		GeeSet* _tmp6_;
		GeeIterator* _tmp7_;
		GeeIterator* _tmp8_;
#line 98 "../src/window.vala"
		_tmp4_ = enigma_main_window_action_accelerators;
#line 98 "../src/window.vala"
		_tmp5_ = gee_multi_map_get_keys (_tmp4_);
#line 98 "../src/window.vala"
		_tmp6_ = _tmp5_;
#line 98 "../src/window.vala"
		_tmp7_ = gee_iterable_iterator ((GeeIterable*) _tmp6_);
#line 98 "../src/window.vala"
		_tmp8_ = _tmp7_;
#line 98 "../src/window.vala"
		_g_object_unref0 (_tmp6_);
#line 98 "../src/window.vala"
		_action_it = _tmp8_;
#line 98 "../src/window.vala"
		while (TRUE) {
#line 2155 "window.c"
			GeeIterator* _tmp9_;
			gchar* action = NULL;
			GeeIterator* _tmp10_;
			gpointer _tmp11_;
			gchar** accels_array = NULL;
			GeeMultiMap* _tmp12_;
			const gchar* _tmp13_;
			GeeCollection* _tmp14_;
			GeeCollection* _tmp15_;
			gint _tmp16_ = 0;
			gpointer* _tmp17_;
			gchar** _tmp18_;
			gint _tmp18__length1;
			gint accels_array_length1;
			gint _accels_array_size_;
			HeApplication* _tmp19_;
			const gchar* _tmp20_;
			gchar* _tmp21_;
			gchar* _tmp22_;
			gchar** _tmp23_;
			gint _tmp23__length1;
#line 98 "../src/window.vala"
			_tmp9_ = _action_it;
#line 98 "../src/window.vala"
			if (!gee_iterator_next (_tmp9_)) {
#line 98 "../src/window.vala"
				break;
#line 2183 "window.c"
			}
#line 98 "../src/window.vala"
			_tmp10_ = _action_it;
#line 98 "../src/window.vala"
			_tmp11_ = gee_iterator_get (_tmp10_);
#line 98 "../src/window.vala"
			action = (gchar*) _tmp11_;
#line 99 "../src/window.vala"
			_tmp12_ = enigma_main_window_action_accelerators;
#line 99 "../src/window.vala"
			_tmp13_ = action;
#line 99 "../src/window.vala"
			_tmp14_ = gee_multi_map_get (_tmp12_, _tmp13_);
#line 99 "../src/window.vala"
			_tmp15_ = _tmp14_;
#line 99 "../src/window.vala"
			_tmp17_ = gee_collection_to_array (_tmp15_, &_tmp16_);
#line 99 "../src/window.vala"
			_tmp18_ = _tmp17_;
#line 99 "../src/window.vala"
			_tmp18__length1 = _tmp16_;
#line 99 "../src/window.vala"
			_g_object_unref0 (_tmp15_);
#line 99 "../src/window.vala"
			accels_array = _tmp18_;
#line 99 "../src/window.vala"
			accels_array_length1 = _tmp18__length1;
#line 99 "../src/window.vala"
			_accels_array_size_ = accels_array_length1;
#line 100 "../src/window.vala"
			_vala_array_add1 (&accels_array, &accels_array_length1, &_accels_array_size_, NULL);
#line 102 "../src/window.vala"
			_tmp19_ = self->priv->_app;
#line 102 "../src/window.vala"
			_tmp20_ = action;
#line 102 "../src/window.vala"
			_tmp21_ = g_strconcat (ENIGMA_MAIN_WINDOW_ACTION_PREFIX, _tmp20_, NULL);
#line 102 "../src/window.vala"
			_tmp22_ = _tmp21_;
#line 102 "../src/window.vala"
			_tmp23_ = accels_array;
#line 102 "../src/window.vala"
			_tmp23__length1 = accels_array_length1;
#line 102 "../src/window.vala"
			gtk_application_set_accels_for_action ((GtkApplication*) _tmp19_, _tmp22_, _tmp23_);
#line 102 "../src/window.vala"
			_g_free0 (_tmp22_);
#line 98 "../src/window.vala"
			accels_array = (_vala_array_free (accels_array, accels_array_length1, (GDestroyNotify) g_free), NULL);
#line 98 "../src/window.vala"
			_g_free0 (action);
#line 2235 "window.c"
		}
#line 98 "../src/window.vala"
		_g_object_unref0 (_action_it);
#line 2239 "window.c"
	}
#line 104 "../src/window.vala"
	_tmp24_ = self->priv->_app;
#line 104 "../src/window.vala"
	_tmp25_ = g_strdup ("<Ctrl>q");
#line 104 "../src/window.vala"
	_tmp26_ = g_new0 (gchar*, 1 + 1);
#line 104 "../src/window.vala"
	_tmp26_[0] = _tmp25_;
#line 104 "../src/window.vala"
	_tmp27_ = _tmp26_;
#line 104 "../src/window.vala"
	_tmp27__length1 = 1;
#line 104 "../src/window.vala"
	gtk_application_set_accels_for_action ((GtkApplication*) _tmp24_, "app.quit", _tmp27_);
#line 104 "../src/window.vala"
	_tmp27_ = (_vala_array_free (_tmp27_, _tmp27__length1, (GDestroyNotify) g_free), NULL);
#line 107 "../src/window.vala"
	_tmp28_ = gtk_builder_new_from_resource ("/co/tauos/Enigma/menu.ui");
#line 107 "../src/window.vala"
	builder = _tmp28_;
#line 108 "../src/window.vala"
	_tmp29_ = self->priv->menu_button;
#line 108 "../src/window.vala"
	_tmp30_ = builder;
#line 108 "../src/window.vala"
	_tmp31_ = gtk_builder_get_object (_tmp30_, "menu");
#line 108 "../src/window.vala"
	gtk_menu_button_set_menu_model (_tmp29_, G_TYPE_CHECK_INSTANCE_CAST (_tmp31_, g_menu_model_get_type (), GMenuModel));
#line 110 "../src/window.vala"
	_tmp32_ = gdk_display_get_default ();
#line 110 "../src/window.vala"
	_tmp33_ = gtk_icon_theme_get_for_display (_tmp32_);
#line 110 "../src/window.vala"
	_tmp34_ = _g_object_ref0 (_tmp33_);
#line 110 "../src/window.vala"
	theme = _tmp34_;
#line 111 "../src/window.vala"
	_tmp35_ = theme;
#line 111 "../src/window.vala"
	gtk_icon_theme_add_resource_path (_tmp35_, "/co/tauos/Enigma/");
#line 114 "../src/window.vala"
	_tmp36_ = self->priv->new_button;
#line 114 "../src/window.vala"
	g_signal_connect_object (_tmp36_, "clicked", (GCallback) __enigma_main_window___lambda9__gtk_button_clicked, self, 0);
#line 115 "../src/window.vala"
	_tmp37_ = self->priv->open_button;
#line 115 "../src/window.vala"
	g_signal_connect_object (_tmp37_, "clicked", (GCallback) __enigma_main_window___lambda10__gtk_button_clicked, self, 0);
#line 116 "../src/window.vala"
	_tmp38_ = self->priv->save_as_button;
#line 116 "../src/window.vala"
	g_signal_connect_object (_tmp38_, "clicked", (GCallback) __enigma_main_window___lambda11__gtk_button_clicked, self, 0);
#line 117 "../src/window.vala"
	_tmp39_ = self->priv->text_box;
#line 117 "../src/window.vala"
	_tmp40_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp39_);
#line 117 "../src/window.vala"
	g_signal_connect_object (_tmp40_, "changed", (GCallback) __enigma_main_window___lambda12__gtk_text_buffer_changed, self, 0);
#line 119 "../src/window.vala"
	enigma_main_window_set_file_name (self, "New File");
#line 120 "../src/window.vala"
	enigma_main_window_set_file_name_ext (self, "new_file.txt");
#line 121 "../src/window.vala"
	_tmp41_ = g_strdup_printf ("%d", enigma_main_window_get_lines (self));
#line 121 "../src/window.vala"
	_tmp42_ = _tmp41_;
#line 121 "../src/window.vala"
	_tmp43_ = g_strconcat (_tmp42_, _ (" lines"), NULL);
#line 121 "../src/window.vala"
	_tmp44_ = _tmp43_;
#line 121 "../src/window.vala"
	enigma_main_window_set_file_line_count (self, _tmp44_);
#line 121 "../src/window.vala"
	_g_free0 (_tmp44_);
#line 121 "../src/window.vala"
	_g_free0 (_tmp42_);
#line 123 "../src/window.vala"
	g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 1, __enigma_main_window___lambda13__gsource_func, g_object_ref (self), g_object_unref);
#line 129 "../src/window.vala"
	_tmp45_ = enigma_settings_new ();
#line 129 "../src/window.vala"
	_data3_->settings = _tmp45_;
#line 130 "../src/window.vala"
	_tmp46_ = _data3_->settings;
#line 130 "../src/window.vala"
	_tmp47_ = enigma_settings_get_font_size (_tmp46_);
#line 130 "../src/window.vala"
	_tmp48_ = _tmp47_;
#line 130 "../src/window.vala"
	_tmp49_ = _tmp48_;
#line 130 "../src/window.vala"
	_tmp51_ = (NULL == _tmp49_) ? 0 : g_quark_from_string (_tmp49_);
#line 130 "../src/window.vala"
	if (_tmp51_ == ((0 != _tmp50_label0) ? _tmp50_label0 : (_tmp50_label0 = g_quark_from_static_string ("'small'")))) {
#line 130 "../src/window.vala"
		switch (0) {
#line 2337 "window.c"
			default:
			{
				GtkSourceView* _tmp52_;
				GtkSourceView* _tmp53_;
				GtkSourceView* _tmp54_;
#line 132 "../src/window.vala"
				_tmp52_ = self->priv->text_box;
#line 132 "../src/window.vala"
				gtk_widget_add_css_class ((GtkWidget*) _tmp52_, "sml-font");
#line 133 "../src/window.vala"
				_tmp53_ = self->priv->text_box;
#line 133 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp53_, "med-font");
#line 134 "../src/window.vala"
				_tmp54_ = self->priv->text_box;
#line 134 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp54_, "big-font");
#line 135 "../src/window.vala"
				break;
#line 2357 "window.c"
			}
		}
	} else if (_tmp51_ == ((0 != _tmp50_label1) ? _tmp50_label1 : (_tmp50_label1 = g_quark_from_static_string ("'large'")))) {
#line 130 "../src/window.vala"
		switch (0) {
#line 2363 "window.c"
			default:
			{
				GtkSourceView* _tmp55_;
				GtkSourceView* _tmp56_;
				GtkSourceView* _tmp57_;
#line 143 "../src/window.vala"
				_tmp55_ = self->priv->text_box;
#line 143 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp55_, "sml-font");
#line 144 "../src/window.vala"
				_tmp56_ = self->priv->text_box;
#line 144 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp56_, "med-font");
#line 145 "../src/window.vala"
				_tmp57_ = self->priv->text_box;
#line 145 "../src/window.vala"
				gtk_widget_add_css_class ((GtkWidget*) _tmp57_, "big-font");
#line 146 "../src/window.vala"
				break;
#line 2383 "window.c"
			}
		}
	} else {
#line 130 "../src/window.vala"
		switch (0) {
#line 2389 "window.c"
			default:
			{
				GtkSourceView* _tmp58_;
				GtkSourceView* _tmp59_;
				GtkSourceView* _tmp60_;
#line 138 "../src/window.vala"
				_tmp58_ = self->priv->text_box;
#line 138 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp58_, "sml-font");
#line 139 "../src/window.vala"
				_tmp59_ = self->priv->text_box;
#line 139 "../src/window.vala"
				gtk_widget_add_css_class ((GtkWidget*) _tmp59_, "med-font");
#line 140 "../src/window.vala"
				_tmp60_ = self->priv->text_box;
#line 140 "../src/window.vala"
				gtk_widget_remove_css_class ((GtkWidget*) _tmp60_, "big-font");
#line 141 "../src/window.vala"
				break;
#line 2409 "window.c"
			}
		}
	}
#line 148 "../src/window.vala"
	_tmp61_ = _data3_->settings;
#line 148 "../src/window.vala"
	g_signal_connect_data ((GObject*) _tmp61_, "notify::font-size", (GCallback) __enigma_main_window___lambda14__g_object_notify, block3_data_ref (_data3_), (GClosureNotify) block3_data_unref, 0);
#line 169 "../src/window.vala"
	_tmp62_ = _data3_->settings;
#line 169 "../src/window.vala"
	_tmp63_ = _tmp62_->settings;
#line 169 "../src/window.vala"
	_tmp64_ = self->priv->text_box;
#line 169 "../src/window.vala"
	g_settings_bind (_tmp63_, "show-line-numbers", (GObject*) _tmp64_, "show-line-numbers", G_SETTINGS_BIND_DEFAULT);
#line 170 "../src/window.vala"
	_tmp65_ = _data3_->settings;
#line 170 "../src/window.vala"
	_tmp66_ = _tmp65_->settings;
#line 170 "../src/window.vala"
	_tmp67_ = self->priv->text_box;
#line 170 "../src/window.vala"
	g_settings_bind (_tmp66_, "hilight-curr-line", (GObject*) _tmp67_, "highlight-current-line", G_SETTINGS_BIND_DEFAULT);
#line 171 "../src/window.vala"
	_tmp68_ = _data3_->settings;
#line 171 "../src/window.vala"
	_tmp69_ = _tmp68_->settings;
#line 171 "../src/window.vala"
	_tmp70_ = self->priv->text_box;
#line 171 "../src/window.vala"
	_tmp71_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp70_);
#line 171 "../src/window.vala"
	g_settings_bind (_tmp69_, "hilight-brackets", (GObject*) G_TYPE_CHECK_INSTANCE_CAST (_tmp71_, gtk_source_buffer_get_type (), GtkSourceBuffer), "highlight-matching-brackets", G_SETTINGS_BIND_DEFAULT);
#line 174 "../src/window.vala"
	gtk_widget_set_size_request ((GtkWidget*) self, 360, 360);
#line 175 "../src/window.vala"
	gtk_widget_show ((GtkWidget*) self);
#line 92 "../src/window.vala"
	_g_object_unref0 (theme);
#line 92 "../src/window.vala"
	_g_object_unref0 (builder);
#line 92 "../src/window.vala"
	block3_data_unref (_data3_);
#line 92 "../src/window.vala"
	_data3_ = NULL;
#line 92 "../src/window.vala"
	return obj;
#line 2457 "window.c"
}

static void
enigma_main_window_class_init (EnigmaMainWindowClass * klass,
                               gpointer klass_data)
{
	GeeHashMultiMap* _tmp0_;
#line 22 "../src/window.vala"
	enigma_main_window_parent_class = g_type_class_peek_parent (klass);
#line 22 "../src/window.vala"
	g_type_class_adjust_private_offset (klass, &EnigmaMainWindow_private_offset);
#line 22 "../src/window.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_enigma_main_window_get_property;
#line 22 "../src/window.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_enigma_main_window_set_property;
#line 22 "../src/window.vala"
	G_OBJECT_CLASS (klass)->constructor = enigma_main_window_constructor;
#line 22 "../src/window.vala"
	G_OBJECT_CLASS (klass)->finalize = enigma_main_window_finalize;
#line 22 "../src/window.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENIGMA_MAIN_WINDOW_FILE_NAME_PROPERTY, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_FILE_NAME_PROPERTY] = g_param_spec_string ("file-name", "file-name", "file-name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 22 "../src/window.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENIGMA_MAIN_WINDOW_FILE_NAME_EXT_PROPERTY, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_FILE_NAME_EXT_PROPERTY] = g_param_spec_string ("file-name-ext", "file-name-ext", "file-name-ext", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 22 "../src/window.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENIGMA_MAIN_WINDOW_FILE_LINE_COUNT_PROPERTY, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_FILE_LINE_COUNT_PROPERTY] = g_param_spec_string ("file-line-count", "file-line-count", "file-line-count", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 22 "../src/window.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENIGMA_MAIN_WINDOW_MODIFIED_PROPERTY, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_MODIFIED_PROPERTY] = g_param_spec_boolean ("modified", "modified", "modified", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 22 "../src/window.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENIGMA_MAIN_WINDOW_ACTIONS_PROPERTY, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_ACTIONS_PROPERTY] = g_param_spec_object ("actions", "actions", "actions", g_simple_action_group_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 22 "../src/window.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), ENIGMA_MAIN_WINDOW_APP_PROPERTY, enigma_main_window_properties[ENIGMA_MAIN_WINDOW_APP_PROPERTY] = g_param_spec_object ("app", "app", "app", HE_TYPE_APPLICATION, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 22 "../src/window.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/co/tauos/Enigma/main_window.ui");
#line 22 "../src/window.vala"
	enigma_main_window_signals[ENIGMA_MAIN_WINDOW_CLICKED_SIGNAL] = g_signal_new ("clicked", ENIGMA_TYPE_MAIN_WINDOW, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "menu_button", FALSE, EnigmaMainWindow_private_offset + G_STRUCT_OFFSET (EnigmaMainWindowPrivate, menu_button));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "new_button", FALSE, EnigmaMainWindow_private_offset + G_STRUCT_OFFSET (EnigmaMainWindowPrivate, new_button));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "open_button", FALSE, EnigmaMainWindow_private_offset + G_STRUCT_OFFSET (EnigmaMainWindowPrivate, open_button));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "save_as_button", FALSE, EnigmaMainWindow_private_offset + G_STRUCT_OFFSET (EnigmaMainWindowPrivate, save_as_button));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "text_box", FALSE, EnigmaMainWindow_private_offset + G_STRUCT_OFFSET (EnigmaMainWindowPrivate, text_box));
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "search_entry", FALSE, EnigmaMainWindow_private_offset + G_STRUCT_OFFSET (EnigmaMainWindowPrivate, search_entry));
#line 75 "../src/window.vala"
	_tmp0_ = gee_hash_multi_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, (GDestroyNotify) g_free, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
#line 75 "../src/window.vala"
	enigma_main_window_action_accelerators = (GeeMultiMap*) _tmp0_;
#line 22 "../src/window.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_search_activate", G_CALLBACK(_enigma_main_window_on_search_activate_gtk_search_entry_search_changed));
#line 2511 "window.c"
}

static void
enigma_main_window_instance_init (EnigmaMainWindow * self,
                                  gpointer klass)
{
#line 22 "../src/window.vala"
	self->priv = enigma_main_window_get_instance_private (self);
#line 39 "../src/window.vala"
	self->priv->_file_name = NULL;
#line 47 "../src/window.vala"
	self->priv->_file_name_ext = NULL;
#line 55 "../src/window.vala"
	self->priv->_file_line_count = NULL;
#line 63 "../src/window.vala"
	self->priv->_modified = FALSE;
#line 22 "../src/window.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 2530 "window.c"
}

static void
enigma_main_window_finalize (GObject * obj)
{
	EnigmaMainWindow * self;
#line 22 "../src/window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindow);
#line 39 "../src/window.vala"
	_g_free0 (self->priv->_file_name);
#line 47 "../src/window.vala"
	_g_free0 (self->priv->_file_name_ext);
#line 55 "../src/window.vala"
	_g_free0 (self->priv->_file_line_count);
#line 71 "../src/window.vala"
	_g_object_unref0 (self->priv->_actions);
#line 82 "../src/window.vala"
	_g_object_unref0 (self->priv->_app);
#line 22 "../src/window.vala"
	G_OBJECT_CLASS (enigma_main_window_parent_class)->finalize (obj);
#line 2551 "window.c"
}

 G_GNUC_NO_INLINE static GType
enigma_main_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (EnigmaMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) enigma_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EnigmaMainWindow), 0, (GInstanceInitFunc) enigma_main_window_instance_init, NULL };
	GType enigma_main_window_type_id;
	enigma_main_window_type_id = g_type_register_static (HE_TYPE_APPLICATION_WINDOW, "EnigmaMainWindow", &g_define_type_info, 0);
	EnigmaMainWindow_private_offset = g_type_add_instance_private (enigma_main_window_type_id, sizeof (EnigmaMainWindowPrivate));
	return enigma_main_window_type_id;
}

GType
enigma_main_window_get_type (void)
{
	static gsize enigma_main_window_type_id__once = 0;
	if (g_once_init_enter (&enigma_main_window_type_id__once)) {
		GType enigma_main_window_type_id;
		enigma_main_window_type_id = enigma_main_window_get_type_once ();
		g_once_init_leave (&enigma_main_window_type_id__once, enigma_main_window_type_id);
	}
	return enigma_main_window_type_id__once;
}

static void
_vala_enigma_main_window_get_property (GObject * object,
                                       guint property_id,
                                       GValue * value,
                                       GParamSpec * pspec)
{
	EnigmaMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindow);
#line 22 "../src/window.vala"
	switch (property_id) {
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_FILE_NAME_PROPERTY:
#line 22 "../src/window.vala"
		g_value_set_string (value, enigma_main_window_get_file_name (self));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_FILE_NAME_EXT_PROPERTY:
#line 22 "../src/window.vala"
		g_value_set_string (value, enigma_main_window_get_file_name_ext (self));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_FILE_LINE_COUNT_PROPERTY:
#line 22 "../src/window.vala"
		g_value_set_string (value, enigma_main_window_get_file_line_count (self));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_MODIFIED_PROPERTY:
#line 22 "../src/window.vala"
		g_value_set_boolean (value, enigma_main_window_get_modified (self));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_ACTIONS_PROPERTY:
#line 22 "../src/window.vala"
		g_value_set_object (value, enigma_main_window_get_actions (self));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_APP_PROPERTY:
#line 22 "../src/window.vala"
		g_value_set_object (value, enigma_main_window_get_app (self));
#line 22 "../src/window.vala"
		break;
#line 2622 "window.c"
		default:
#line 22 "../src/window.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 22 "../src/window.vala"
		break;
#line 2628 "window.c"
	}
}

static void
_vala_enigma_main_window_set_property (GObject * object,
                                       guint property_id,
                                       const GValue * value,
                                       GParamSpec * pspec)
{
	EnigmaMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, ENIGMA_TYPE_MAIN_WINDOW, EnigmaMainWindow);
#line 22 "../src/window.vala"
	switch (property_id) {
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_FILE_NAME_PROPERTY:
#line 22 "../src/window.vala"
		enigma_main_window_set_file_name (self, g_value_get_string (value));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_FILE_NAME_EXT_PROPERTY:
#line 22 "../src/window.vala"
		enigma_main_window_set_file_name_ext (self, g_value_get_string (value));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_FILE_LINE_COUNT_PROPERTY:
#line 22 "../src/window.vala"
		enigma_main_window_set_file_line_count (self, g_value_get_string (value));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_MODIFIED_PROPERTY:
#line 22 "../src/window.vala"
		enigma_main_window_set_modified (self, g_value_get_boolean (value));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_ACTIONS_PROPERTY:
#line 22 "../src/window.vala"
		enigma_main_window_set_actions (self, g_value_get_object (value));
#line 22 "../src/window.vala"
		break;
#line 22 "../src/window.vala"
		case ENIGMA_MAIN_WINDOW_APP_PROPERTY:
#line 22 "../src/window.vala"
		enigma_main_window_set_app (self, g_value_get_object (value));
#line 22 "../src/window.vala"
		break;
#line 2678 "window.c"
		default:
#line 22 "../src/window.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 22 "../src/window.vala"
		break;
#line 2684 "window.c"
	}
}

static void
_vala_array_destroy (gpointer array,
                     gssize array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gssize i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_vala_array_free (gpointer array,
                  gssize array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

