/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APP_ID "co.tauos.Enigma"

#define DEVELOPMENT 0

#define GETTEXT_PACKAGE "co.tauos.Enigma"

#define LOCALEDIR "/app/share/locale"

#define NAME_SUFFIX ""

#define VERSION "0.1.0"

